### ISSUE TITLE
Can not embed a Youtube player anymore

### ISSUE THREAD

**Issue by StefanPetrick** [arduino/forum-issues#100]
In the old forum a youtube address in the post embedded a small player.

That does not work anymore and the old posts contain only plain text now.

Example here: http://forum.arduino.cc/index.php?topic=238567.30

**Comment by ovisopa** [comment]
Guys, but what security threats is youtube making to your forum ? I don;t understand where is the security issue for embeding youitube videos? I'm not saying to allow embeded flash files, but just youtube video.

Can anyone tell us more details, why this normal/usual/usefully function is disabled ? 

Thank you.

**Comment by Chris--A** [comment]
> Guys, but what security threats is YouTube making to your forum ?

As long as the embed code is restricted to trusted websites like youtube (which it was, as SMF converted a plain text URL into the embed).

The only other reason for a block is because the content of the embedded videos is not controlled.

**Comment by ovisopa** [comment]
For the content of the videos, I think the forum has a few moderators that can ban or delete some post if the content is inappropriate, but this is not a reason to make visualization of all users harder.

I really think it's time to rethink why the bbcode was removed, this is one of the few forums that doesn embed youtube videos automatically.

**Comment by per1234** [comment]
It's working again after the switch to using the Discourse software for the Arduino forum this week.
