### ISSUE TITLE
Numeric user names? This is ridiculous!  

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#105]
Here are some user names that have registered to use the forum:

```
157426
30792
239399
214153
```

And so on. Pages of them.

Can't we enforce that user names have to have a few alphabetic characters? This is just abuse of process.

Otherwise we'll have people like:

```
000111000
OOOIIIOOO
0O01I10O0
```

If people can't make up a name with letters of the alphabet in them, I suggest we don't want them.

**Comment by nickgammon** [comment]
Is this bug report just being ignored? I still think it is silly to allow user names like:

```
.
0
1
1000100
1000101
10010
100100
10010001
111111
```

One guy has his "display name" as "..".

This is ridiculous. How can you refer to people as "as . said" or "I agree with ..". 

Surely we can insist that forum names have at least some letters in them. Certainly not all digits, nor all punctuation. To confuse things more, we have two members called 7:

```
15673 	7 	ftaba 	email_redacted		1907 days ago 	0 	
237422 	7 	7 	email_redacted 	115.242.25.252 	342 days ago 	0
```

How does this happen? How can we have two users named 7? What if one 7 insults us? What if the other 7 gets the blame?

**Comment by RobTillaart** [comment]
Can we ban them for having a ridiculous name ...? 
still a real nerd want to use 01000010 == 0x42  or 0x2A == 42

**Comment by Chris--A** [comment]
> This is soo 1337

Can't forget those that like to use everything but the alphabet to convey a message.

A good portion of the ID's that are *silly* are probably spammers. But back in the day (not sure if still is the case) you needed to be logged in to view attachments. This would have provoked numerous registrations just to view something relevant to the user.

I think with proper spam control and ease of access, the registration system will still get silly names, but they might have a higher chance of being active on the forum.

Its a pain for moderators I agree, but that should be part of the user control. Maybe moderation screens could show the users first name in brackets : *1000100<sup>(steve)</sup> or 1000101<sup>(bruce)</sup>*

**Comment by matteosuppo** [comment]
I believe the registration of new users is not related to the forum at all, but to the Arduino registration system.

**Comment by nickgammon** [comment]
So that's it? Can't the Arduino registration system be improved?

**Comment by mastrolinux** [comment]
Yes and it will be but is not a forum issues to be handled here.
Il 09/mar/2015 20:48 "Nick Gammon" <notifications@github.com> ha scritto:
