### ISSUE TITLE
Where did the "report to moderator" link go?

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#112]
I just saw a post that looked like spam, and wanted to report it because I wasn't sure. But I can't find the "report to moderator" link.

![screenshot from 2014-10-31 21 02 52](https://cloud.githubusercontent.com/assets/185088/4858979/48d535b2-60e5-11e4-8b24-503c6146ffdb.png)

...

![screenshot from 2014-10-31 21 03 10](https://cloud.githubusercontent.com/assets/185088/4858983/4ea18536-60e5-11e4-9031-54118ef41f2f.png)

Have I gone blind? Where is it?

**Comment by per1234** [comment]
I agree that this is a useful thing. The Discourse forum software now in use allows moderators to cast flags on any post so I'll close this as resolved.
