### ISSUE TITLE
Suggest "boilerplate message" when users start a new thread

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#113]
On my own forum (about online games) I have a "boilerplate" message which appears at the top of the page when users start a **new** thread. Not when replying, and not when viewing.

The reason for this is that starting a new thread is a serious business, and you want (hope) that they will follow the forum rules when doing so.

For example:
- Don't cross-post
- Post your code
- Use code tags
- Post your error message
- Post a link to the device which is not working for you.

Below is what you see on my forum:

![screenshot from 2014-11-01 07 35 52](https://cloud.githubusercontent.com/assets/185088/4868268/38822b12-613e-11e4-95bf-83784a63b9cd.png)

Each forum section has its **own** boilerplate, which allows customization for:
- Language (eg. English, Italian)
- What is required (eg. a schematic for an electronics question, code for a programming question)
- Useful links relevant to this part of the forum (eg. electronics links, programming links)

The boilerplate itself could use bb codes so we can put lists, bold, hyperlinks, etc. in them.

You could make the boilerplate updateable by moderators, who usually have a good idea of what is going on in each part of the forum.

This could reduce frustration somewhat, as people clearly don't always read the FAQ or forum guidelines, but the boilerplate is "in your face" when you go to open a new thread.

**Comment by per1234** [comment]
The Discourse forum software that was switched to this week has a functionality similar to what is requested here. The following is displayed in the post composer during the user's first two posts:

> Welcome to Arduino Forum — thanks for starting a new conversation!
> 
> - Does the title sound interesting if you read it out loud? Is it a good summary?
> - Who would be interested in this? Why does it matter? What kind of responses do you want?
> - Include commonly used words in your topic so others can find it. To group your topic with related topics, select a category (or tag).
> 
> For more, see our [community guidelines](https://forum.arduino.cc/guidelines). This panel will only appear for your first 2 posts.

I realize this doesn't have the "only when starting a thread" behavior, but I don't see any reason to restrict this to topic creation. It's always important for people to be aware of the rules, whether they are creating a topic or making a reply.

Discussion is currently in progress about whether we can incorporate the information from Nick Gammon's excellent ["How to use this forum - please read" guide](https://forum.arduino.cc/t/how-to-use-this-forum-please-read/145337) with the linked "community guidelines" document (it's currently just the default content provided by Discourse). @nickgammon, you're very welcome to participate in [that conversation](https://forum.arduino.cc/t/how-to-get-the-best-comments-and-help/848893/15).
