### ISSUE TITLE
Deleting a user who you have already deleted, offers to delete your OWN account

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#124]
I saw a spammer, and went do delete him and his account like this:

![screenshot from 2014-11-06 16 13 42](https://cloud.githubusercontent.com/assets/185088/4931216/1262f724-6574-11e4-9918-bcf6f76dd8a7.png)

That drop-down "Replies to topics" is the default. Usually I select "Topics and posts" but thought "well the default is probably more powerful." Wrong!

So after doing that I noticed that while the user was deleted, his **post** was still there:

![screenshot from 2014-11-06 16 10 45](https://cloud.githubusercontent.com/assets/185088/4931223/3f2468b0-6574-11e4-99d9-9e41293aeafe.png)

<sigh> So I see if I can delete it again "properly" this time, and select "Delete user" (which is still available in the menu, even though he is now deleted). But, uh oh!

![screenshot from 2014-11-06 16 11 04](https://cloud.githubusercontent.com/assets/185088/4931227/5afb6a0c-6574-11e4-81ea-954a0dc0850f.png)

No I most certainly do not want to delete **my** account! Why would I do that? This is a massive hole that some moderator could fall into, if they go to delete an account that another moderator has just deleted, and skim the confirmation screen as meaning "are you sure you want to delete this user?".

Please change this so that you cannot delete your own account, when attempting to remove spam.

**Comment by matteosuppo** [comment]
Is this still happening or has been fixed?

**Comment by nickgammon** [comment]
I tried to reproduce but got:


> **An Error Has Occurred**
> Token verification failed. Please go back and try again.

That was on the first attempt at deleting. So I'm unsure.

**Comment by per1234** [comment]
Closing as fixed by this week's switch to a new forum software. If anyone still experiences this issue, please comment here and I'll reopen.
