### ISSUE TITLE
Attempting to post to a locked thread gives weird error message

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#128]
I was editing the first (original) post in a thread because the OP had deleted his code, and his question, to our annoyance. In the process I checked "Lock this topic" checkbox, so that the OP wouldn't edit the post and delete it again.

(Thread: http://forum.arduino.cc/index.php?topic=277436 )

However when I went to post it (the amended first post) I got this message:

![screenshot_from_2014-11-08_14 42 29](https://cloud.githubusercontent.com/assets/185088/4963139/e253d634-66f9-11e4-8ec4-ff57f72740cb.png)

This doesn't make any sense.

Working through it:
- I gather another moderator locked the topic while I was finding the code to put back into the original post.
- Thus the thread is now locked.
- However since I had **also** checked "lock this topic" no harm is done.
- But the message says I have to **uncheck** "lock this topic" if I want it to stay locked.
- Huh?

Why should I uncheck "lock this topic" to **keep it locked**?

**Comment by matteosuppo** [comment]
I'm going to change it to "Warning - while you were typing the topic was locked. Please uncheck the "Lock this topic" box under "Attachments and other options" below if you wish to unlock it"

**Comment by matteosuppo** [comment]
No wait, it means that if you do not uncheck the box you cannot post it.

**Comment by matteosuppo** [comment]
"Warning - while you were typing the topic was locked. Please uncheck the "Lock this topic" box under "Attachments and other options" below to save your message and unlock the topic"

**Comment by nickgammon** [comment]
It's not the wording of the message that is the issue.

* Make a test post
* Reply to the test post, along the lines of "this discussion is now closed - moderator" **and** lock the thread (expand "Attachments and other options" and check "Lock this topic").
* You cannot make the post - it says *Warning - while you were typing the topic was locked. Please uncheck the "Lock this topic" box under "Attachments and other options" below if you do not wish to undo this action.*

It wasn't locked "while I was typing" - I locked it as part of the post options.

First, being a moderator I should be able to post to a locked thread.
Second, it should make the post, and then lock the thread.

This used to work. It isn't a feature request. This is a bug report.

**Comment by nickgammon** [comment]
If I do it as separate actions, I can achieve it:

* Make a reply
* Go back and lock the thread
* I can still reply to the locked thread as I am a moderator

The test (which generates the error message) should, at the very least, respect the moderator flag. This is just a bogus "you can't do that" message because I **can** - if I do it as two steps!

**Comment by per1234** [comment]
Fixed by this weeks switch to the Discourse-based forum.
