### ISSUE TITLE
disable 'Profile Info' button in user profile dropdown

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#13]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Wednesday Sep 10, 2014 at 15:57 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/13_

---

https://www.dropbox.com/s/izmcmqh1w2153pe/Screenshot%202014-09-10%2017.57.06.png?dl=0

**Comment by per1234** [comment]
Closing as obsoleted by the change to a Discourse based forum this week.
