### ISSUE TITLE
Merged/moved redirect links stay "New" even after reading

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#145]
After merging threads, or moving a thread, a "redirect" link is left which is permanently "New", for example:

![screenshot from 2014-11-22 07 00 50](https://cloud.githubusercontent.com/assets/185088/5148712/b57f4680-7215-11e4-8fd5-7f4cacfc02ab.png)

I have followed that link a number of times, but it stays "New". This is confusing because it is not new once I have followed it, and as you can see the thread it points to "Email notifications fix planned for release on 2014-11-25" (underneath) is not new.

This is annoying, because if someone other than you created the merged/moved thread, you may be fooled into thinking that you need to read it. Considering how slow the forum is at present, reading a thread when you don't have to is a waste of time.

**Comment by matteosuppo** [comment]
Does it still happen? I can reproduce it

**Comment by nickgammon** [comment]
If you can reproduce it, yes it it. ;)

It just happened to me, yes.

**Comment by matteosuppo** [comment]
I asked because I tried on the development forum and it didn't happen to me
