### ISSUE TITLE
I thought the new forum was supposed to reduce spam

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#146]
How can someone make a post like this?

```
Maria To Be Arrive at a new plane center


http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n22jg/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n22nm/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n23ir/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n23kd/


http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n22gs/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n22p6/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n22ru/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n22uf/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n22y6/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n23gb/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n23m3/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n23p7/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n23s1/
http://xxxxxxxxxxxxxxxxxxxxxxxxxx/2n23u9/
```

(URLs redacted).

That is 99% spam, 1% ham.

I accept that a new user might post a question with a couple of hyperlinks, but arguing that the new forum was necessary to "reduce spam" doesn't seem to cut it.

Can't some sort of test be applied to posts, of a completely new user, that their post has to be 90% ham, and only 10% links to some other sites?

I only spotted this because of the ridiculous thread title. I bet a fair few get through, until someone reports them to the moderator, a report which I am not currently receiving.

**Comment by nickgammon** [comment]
Posts deleted today:

* BUY ITALIAN NOVELTY PASSPORT/DANISH FAKE PASSPORT SALE 
* Original novelty passports Drivers License Id card visa 
*  BUY NORVERTY FAKE/REAL PASSPORTS, DRIVER LICENCE, IDS, 

All by jennyadams55.

Deleted at different times (so therefore by different moderators).

How come, after all these improvements, a post with "fake passport" can still be made and not picked up somewhere?

How come the same user can make multiple posts, apparently after being deleted?

**Comment by mastrolinux** [comment]
Looks like a bug in the login system probably we do not cancel the session after the user is deleted. Going to verify this one.

**Comment by mastrolinux** [comment]
We now remove the session of the user in the SSO, needs further action to delete it for the forum as well.
