### ISSUE TITLE
Forum down, reports "no_board"

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#148]
> no_board

What can I say?

Can't you have a fallback message, like "Sorry, we are doing maintenance, between x and y hours GMT, we apologize for the inconvenience." ?

![screenshot_from_2014-11-25_21 10 01](https://cloud.githubusercontent.com/assets/185088/5181463/ce621948-74ea-11e4-92f3-35b52d4c0b41.png)

For a site that gets 1.3 million hits a day, this doesn't look professional.

**Comment by mastrolinux** [comment]
Closing this. @nickgammon we are barely at 76k sessions/day so please stop saying we hit > 1 millions/day on the forum.

**Comment by nickgammon** [comment]
As you wish, however Wolfram Alpha says differently:

![screenshot from 2015-03-06 16 57 41](https://cloud.githubusercontent.com/assets/185088/6520891/0c3fa09c-c422-11e4-8af4-fa4e1a7c16b4.png)

**Comment by mastrolinux** [comment]
Yes they are collecting all the data from our websites. *.arduino.cc has so many visits, the forum is about 4-5% of the visits. 
They are not able to split data in our subdomains http://m.wolframalpha.com/input/?i=Arduino.cc+Vs+forum.arduino.cc&x=0&y=0
I am speaking reading the Google analytics and load balancer logging report.
