### ISSUE TITLE
Deleting all messages, which are months old, should not be possible

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#151]
See: http://forum.arduino.cc/index.php?topic=282897.0

It seems a moderator accidentally deleted all the posts for a user, who had reported a spammer. Due to some confusion, the _reporting user_ was deleted instead of the spammer.

The user, accidentally deleted, has posts going back to **January 2013**. Frankly, the forum should not allow anyone (except maybe with multiple confirmations) to delete posts almost two years old (if then). Such posts are part of threads, and the thread makes no sense with holes punched out of them.

I think we can assume that a post which survives a month, is almost certainly legitimate, and letting moderators click on a "delete all posts" button, without realizing he is removing hundreds of posts, spanning two years, is ridiculous.

If you are going to let this happen at all, instead of a wimpy "are you sure?" dialog, it should display a lot more information. Such as ("300 posts will be deleted, the earliest being January 2013").

This dialog simply isn't good enough:

![screenshot from 2014-12-02 16 55 27](https://cloud.githubusercontent.com/assets/185088/5258561/d58929fa-7a44-11e4-843b-e4980c7987c8.png)
- There is no confirmation, on that page, even **whose** account is being deleted!
- No confirmation about _how many posts_ will be deleted, or what date range they span. 
- No confirmation about when the user joined.

All those things might make a moderator pause, before hitting the OK button.

---

I still say that it should not be possible, without a lot of effort, to delete posts which have survived for a month or two. Spam is picked up within a day, abuse maybe a day or two later. You simply should not be able to delete posts which are months old, except maybe one by one.

**Comment by per1234** [comment]
The new Discourse based forum is now configured so it is not possible to delete all posts of a user if there are more than 15. It also prevents deletion of any posts older than 60 days (these can only be anonymized). So I think this can be considered resolved now.
