### ISSUE TITLE
Token verification failed when I close a mod. report 

### ISSUE THREAD

**Issue by leomil72** [arduino/forum-issues#153]
When I try to close a moderation report, the first time I get this:

An Error Has Occurred
Token verification failed. Please go back and try again.

The second time the operation is correctly executed. This has never happened to me before.

**Comment by matteosuppo** [comment]
Does it still happens?

**Comment by per1234** [comment]
Hi @leomil72. Thanks so much for reporting this very annoying bug.

>Does it still happens?

We suffered with it up until the very last moment of the SMF forum's life. But it doesn't happen any more now that the forum was switched to the Discourse software this week. So I'll close this as resolved.
