### ISSUE TITLE
Noticed a few problems after latest update.

### ISSUE THREAD

**Issue by Chris--A** [arduino/forum-issues#156]
Posts are showing dual `[Add Karma]` buttons. (was one of these meant to be the karma count?)

Last post info now is set to 8% width which causes the info to take 3 lines, and could really be on one line when using large screens. Wasted space was dismissed here #137 as a 'usual thing', however this is pretty terrible (expands the content by 20 lines per page).

**Comment by smeezekitty** [comment]
Old issue but STILL BROKEN
