### ISSUE TITLE
Set up robots.txt to ignore the development forum

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#160]
I used Google today to find an old thread, namely searching for:

```level interrupt site:arduino.cc christensen jack```

I found the thread I wanted ("Which external interrupt to wake 328P? - Page 2") and typed a reply. Then I was surprised to find the latest post in that part of the forum was October 21, 2014.

Closer inspection revealed that the Google link led to: http://forum.dev.arduino.cc/index.php?topic=179873.0

(Notice the "dev" in the link). I had accidentally reached the development forum. This is an easy mistake to make.

I suggest that a "robots.txt" file be added to the **development** forum to stop the Google spider from indexing the development forum. That way people searching for Arduino-related items are sent to the live forum.

**Comment by mastrolinux** [comment]
It was done some time ago. http://forumdev.arduino.cc/robots.txt
