### ISSUE TITLE
Suggestion for detecting spam

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#162]
You know, I can usually pick spam just from the thread title. Here are some examples from today:

* Forward my lap you're right this 
* He continued in his exercise equipment room
* Buy Real/Fake Passports,Driver’s License,ID Cards,Visas, USA
* Top Quality Documents Homes - Purchase Real and Novelty Passports,id cards,
*  Buy Real/Fake Passports,Driver’s License,ID Cards,Visas, USA Green Card,Citizens
* Best Counterfeit EURO & DOLLAR NOTES,PASSPORTS,ID,
* Buy Real Genuine data base Registered and driving licenses

How about this?

For moderators, show a list of new threads, started by people with no posts (ie. this is their first post) with the thread title and a link to check the thread out. Then have a big button: [ SPAM ]

This could appear at the top of every page. And maybe have a [ NOT SPAM ] button, so we can quickly eliminate posts that are genuine.

I'm still surprised that with this new forum, we can't **auto-detect spam**, like "passports". Who the hell needs passports to do electronics? Come on, this isn't rocket science.

**Comment by nickgammon** [comment]
The first spam post reads:

> Forward my lap you're right this in the mirror image process gauge place attorney he loved his engage in the cafe and loss walking %eh answer me on Reach Out grab the ball usual czar power on remember stern are back drop the ball this is all dynamic
> 
> alpha shred
> 
> just rose leveled up imaginary ball grapples this cable and again we're going to work live sax triceps NHS here cable fully and work a lot goal 3 shoot what Ashley's .

Clearly they are filling up the post with garbage to defeat Bayesian filters. But really, can't we outsmart these guys? They might be smart, but we are smarter, right?

**Comment by Chris--A** [comment]
An effective mechanism would be a simple honey pot on the 'New topic' page. Combine that with another text box containing some text saying "Remove this text to post" (possible language problem).

Then on the server, a check to ensure the honey pot is still empty, and the text has been removed from the second field will allow the server to reject bots effectively. 

Of course its useless against targeted attacks, but I would argue that it will eliminate almost all of the random spam/advertising posts which is what we seem to be viewing. (targeted attacks would be in high volume, like in the past where 100,000 users were registered in a short time).

**Comment by mastrolinux** [comment]
@matteosuppo please give us a time evaluation for this task. It could be very handful.

**Comment by matteosuppo** [comment]
Or we could add a captcha for the first message someone posts.

Il giorno lun 12 gen 2015 12:26 Luca Cipriani <notifications@github.com> ha
scritto:

**Comment by nickgammon** [comment]
I think spammers are able to work around captchas by now. They are probably working from home being paid practically nothing, and getting paid per message they manage to post. If they have to type in a captcha they will. What we need is a quick way of responding. Plus, as I have said many times, and I'll say it again, how come a message with "fake passport" in the title is even allowed to be posted?

**Comment by nickgammon** [comment]
After seeing another spam post, I think "testosterone" is another word that doesn't generally appear in electronics or programming circles.

**Comment by nickgammon** [comment]
One thing that would be useful in combating spam here is to identify the nature of our attackers. My first questions would be:

* Are most spammers humans, or bots?
* Are most spammers attacking SMF forums in general, or this forum in particular?

Now if we find that most spammers are bots, then a simple question that is easy for a human to answer but hard for a bot, would help. For example, show pictures of a dog, a train and an aeroplane, and ask them to "tick" the dog (randomizing the order of the images, of course).

A human can answer that easily, a bot would have to interpret the image.

And if SMF is being attacked (but not us in particular) then fudging a "signature" that identifies us as an SMF forum, or changing the field names on forms, might slow bots down.

If we are not being attacked specifically (only because we use SMF) then an extra page that people have to negotiate for their first few posts might slow bots right down, because that is not standard SMF procedures. Such as, "what is 5 + 7?". Or "click on the ostrich".

To answer my questions, and therefore fine-tune our spam response, we could trial something like the idea of identifying the picture of the dog. If that slows spam down, then we are being attacked by bots. If it doesn't, then we are being attacked by humans.

**Comment by nickgammon** [comment]
I just saw an interesting variation on the captcha:

![screenshot from 2015-01-15 07 48 33](https://cloud.githubusercontent.com/assets/185088/5747278/ff07da84-9c8a-11e4-967a-fb9c52dfef10.png)

The letters are fairly easy to read, but you don't type **all** of them in. This might slow down computer-recognition schemes because they have to "look up" to see which letters are to be incorporated in the response.

**Comment by mastrolinux** [comment]
With the new filter in place can I close this issue?

**Comment by nickgammon** [comment]
The new system seems to be working well, so yes you can close it. (Or I will).
