### ISSUE TITLE
Cannot access Learning -> Reference

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#163]
Clicking on Learning -> Reference (as shown) returns a blank page with this as the URL:

https://id.arduino.cc/auth/login/?go=1%26returnurl%3Dhttp%3A%2F%2Farduino.cc%2Fen%2FReference%2FHomePage

![screenshot from 2015-01-11 07 09 21](https://cloud.githubusercontent.com/assets/185088/5693056/fd619d00-9960-11e4-8205-242902e5e1c8.png)

Raised here: http://forum.arduino.cc/index.php?topic=291439

**Comment by mastrolinux** [comment]
Can you confirm this is now solved?

**Comment by nickgammon** [comment]
Seems OK today.
