### ISSUE TITLE
Forum shows incorrect time

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#164]
I am in Melbourne, Australia, which at present is in the time zone UTC+11. Proof:

![screenshot from 2015-01-14 15 57 36](https://cloud.githubusercontent.com/assets/185088/5734283/44ff188e-9c06-11e4-9749-fe57a4417e36.png)

Accordingly, I set my forum profile to have the time zone UTC+11:

![screenshot from 2015-01-14 15 57 14](https://cloud.githubusercontent.com/assets/185088/5734287/542ebe04-9c06-11e4-8611-21be19321849.png)

However a post I made a couple of minutes ago is shown as 2:52 pm, not 3:52 pm, which it should have:

![screenshot from 2015-01-14 15 58 09](https://cloud.githubusercontent.com/assets/185088/5734290/6971d2ec-9c06-11e4-8d0e-473623ec4827.png)

Therefore the forum is out by an hour.

**Comment by matteosuppo** [comment]
Is this still happening?

**Comment by nickgammon** [comment]
Yes, I just made a post at 6:44 a.m. and it appeared on the forum as 5:44 a.m. My time zone is correct (UTC + 11 hours). I guess the forum itself is not set to the correct time. Does it not happen to you? Try making a test post.

**Comment by matteosuppo** [comment]
No, it shows the correct date to me. I'll try changing my time zone

**Comment by matteosuppo** [comment]
There are two different +11 time zones. One is Vladivostok (the one you have selected) and the other is Solomon island.

By selecting Solomon Island the time should be correct.

**Comment by nickgammon** [comment]
What, you've lost me there. That's like saying there are two versions of the number 42, one is larger than the other one. Are you saying that one includes daylight savings and one doesn't? That isn't clear. And I'm not in the Solomon Islands, how am I supposed to know to choose that?

Anyway, I fixed it by choosing Sydney (which is in the same time zone as I am). I'm pretty sure I had previously chosen Vladivostok to manually allow for daylight saving time.

It isn't clear that the forum allows for daylight saving automatically.

**Comment by matteosuppo** [comment]
Unfortunately time zones are a bit of a mess In the first place. The
different time zones with +11 allow for different ways to consider daylight
saving (which is another mess).

Il giorno mar 17 mar 2015 20:26 Nick Gammon <notifications@github.com> ha
scritto:

**Comment by nickgammon** [comment]
I won't argue with you. Anyway I suppose it is fixed now. :)
