### ISSUE TITLE
Clicking the Download links leads to a blank page

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#166]
If I click the "Download" link (to download the Arduino software) it redirects to this link:

https://id.arduino.cc/auth/login/?go=1%26returnurl%3Dhttp%3A%2F%2Farduino.cc%2Fen%2FMain%2FSoftware

That opens a blank page (presumably the server crashed).

Ditto for "Products":

https://id.arduino.cc/auth/login/?go=1%26returnurl%3Dhttp%3A%2F%2Farduino.cc%2Fen%2FMain%2FProducts

So I think we can say the server is in **degraded** mode.

**Comment by nickgammon** [comment]
Also see: http://forum.arduino.cc/index.php?topic=292734

Apparently Tutorials isn't working too well either.

**Comment by nickgammon** [comment]
Also see https://github.com/arduino/forum-issues/issues/163

Learning -> Reference is also down.

Can't something be done to make the site more reliable?

**Comment by mastrolinux** [comment]
We had a major outage in the main website. just fixed. Refining the last things to finally have status.arduino.cc

**Comment by mastrolinux** [comment]
I added an extra disk to the main site and now we have proper monitoring on disk space. Closing this issues
