### ISSUE TITLE
"Real" forum search is missing

### ISSUE THREAD

**Issue by Elijahg** [arduino/forum-issues#167]
Where has the real search gone that we had in the previous version of the forum software? Crappy Google custom search is no replacement! How can you only search within specific fora with Google search? How can you restrict to a particular user? What if I want to search for posts that were made today, not when Google's bot decided to crawl the forum? Or between a specific date range?

**Comment by matteosuppo** [comment]
You can still access it from http://forum.arduino.cc/index.php?action=search

There should probably be a link somewhere.

**Comment by matteosuppo** [comment]
On a second check it appears the search is broken. I'll investigate into it.

**Comment by teo1978** [comment]
Also there seems to be no way to **search within a given thread**.
That's basic forum functionality. 

Seriously, this is ridiculous

**Comment by per1234** [comment]
There is now a native forum search once more:
https://www.arduino.cc/search?q=arduino&tab=forum

**Comment by Elijahg** [comment]
Thanks for the update!
