### ISSUE TITLE
Terrific nicknames

### ISSUE THREAD

**Issue by leomil72** [arduino/forum-issues#168]
How is it possible that a user signed up with this nickname: ..??? Yeah, you'd read correclty, just two dots. Nothing more! o__O
http://forum.arduino.cc/index.php?action=profile;u=155293

Ok, it comes from the old forum, but is there a filter or something else that blocks this kind of nicknames? And, is there a way to force that user to change his nickname?

**Comment by nickgammon** [comment]
\<sigh\>

See: https://github.com/arduino/forum-issues/issues/105
