### ISSUE TITLE
You are Already logged in

### ISSUE THREAD

**Issue by bgma** [arduino/forum-issues#169]
Hi,
When I try to log on arduino.cc I come to what I assume is the front page. When I try to access the forums I get the message "You are Already logged in. (If You Are Not Automatically redirected in seconds, click here ...)" and here it remains forever. If I click on "click here ..." I will return to the front. If I select the "Forum Settings" same thing happens.

What to do about it?

**Comment by matteosuppo** [comment]
I believe it was a situation that is now resolved. Can you confirm?

**Comment by bgma** [comment]
The problem is still there!

**Comment by matteosuppo** [comment]
Did you try with a different browser? Maybe it's a cache issue

**Comment by bgma** [comment]
Yes, IE10 and Firefox 34.0.5 running on W7x64.
I have also tried with a different user.
 
Date: Mon, 9 Mar 2015 08:21:29 -0700

**Comment by bgma** [comment]
I've also tried
"microsoft security Essentials"  on and off,
"symantec endpoint protection" on and off.
 
Date: Mon, 9 Mar 2015 08:21:29 -0700

**Comment by matteosuppo** [comment]
Can you please provide a screenshot?

**Comment by bgma** [comment]
![42](https://cloud.githubusercontent.com/assets/10388645/6696939/4a14f466-cced-11e4-9d50-8d3b37658dd4.png)


![41](https://cloud.githubusercontent.com/assets/10388645/6696861/afe8f69e-ccec-11e4-9bd7-903a4e6211d8.png)

**Comment by mastrolinux** [comment]
This is a SSO known issue, we can close the issue here and keep it in the SSO repo.

**Comment by bgma** [comment]
When will this be fixed?
I still can not use the site as logged in
 
Date: Wed, 18 Mar 2015 01:15:07 -0700

**Comment by bgma** [comment]
Now it works.
Thanks!
