### ISSUE TITLE
CODE TAGS ICON

### ISSUE THREAD

**Issue by TomGeorge1956** [arduino/forum-issues#174]
Please..please..please make the CODE Tag Icon, HUGE in the menu list, it is the most abused facility of the text editor.
Do NOT JUST USE A GRAPHIC please, write on it Code Tag.
And use colours of higher contrast, the small fine details of the icons at the moment are disappearing in the sickly yellow background.
Or have a button that says code tag.

90% of new users do not know its there, yet in the forum version previous to this it seemed everybody new how and where it was, without prompting.
ON SOAPBOX
Come on guys I know its a bugger of a job, but we the users are getting no feedback from you as to whats going on.
Please provide a button to press that lists the latest things that are happening in the upgrade of the site, even if it has no reply facility it will keep us informed.
OFF SOAPBOX,,,, oh I'd like a on soapbox, off soapbox icon as well.

Tom.....

**Comment by matteosuppo** [comment]
Hello, we are evaluating the request. May I personally ask what do you mean by ON SOAPBOX and OFF SOAPBOX? Is it a reference to a feature present in the previous forum version? I wasn't around at the time so I don't understand

**Comment by TomGeorge1956** [comment]
Hi, thanks for the reply, its like we are going unanswered to our problems.The soapbox bit a bit of a joke, if any of us want to get on our soapbox and express an opinion, it would be nice to have it highlighted as such, So that only the very few interested need to read it. Don't worry about it, is just a joke.
The KARMA is one of the biggest problems and the fact that the Reply MENU bar has such small icons, and no written text with them.
I would be happy to have larger icons with "Code" "Quote" "Image" actually written in it.
The number of new members who post code without code tags is escalating to the point that just about any new member first post will not put code in tags  and has have it pointed out.
BIG is beautiful ,small is like small print, needs to be read but nobody can bother because it is to damn difficult or not noticed.
Tom......

**Comment by M-square** [comment]
Cut-n-paste from my argument in http://forum.arduino.cc/index.php?topic=318297.msg2202133#msg2202133 

In the current web page for creating a post the codetag icon is the 19th icon. I think it looks like a scroll of ancient papyrus with anglebrackets in front. Now, I am not a great fan of Egyptian hireoglyphics, so I do not associate that with "code". Yes, one can hover over the icon and get an explanation; however: there are the obvious icons Bold, Italics, Leftjustify, bullet list - obvious becasue they are the same in Word and OpenOffice - and there are 10 non-obvious icons that you need to hover-mouse-over to understand.

The newbie is in a hurry. As we all know to well, they do not have time to read all of Nick's excellent sticky "How to use the Forum" (which require another click to follow the link to the full post unless you're in the Troubleshooting section).

Lets think for a moment. What is the most used formatting in a post? Is the Bold? The "glowing text"? "Insert a table"? No, it is of course "Code Tags". From a simple usability point of view it should be the FIRST ICON  IN THE LIST, and if possible it should say CODE (not a fancy icon).

**Comment by TomGeorge1956** [comment]
I agree, as I said the icons are too small, I notice nothing appears to have been done to fix any problems.
The email notification still doesn't work, karma is still a mystery.
Tom
