### ISSUE TITLE
Banning a user bans the user AND the moderator doing the ban!

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#176]
Pfft!

I just tested banning a user after reading this suggestion from Matteo Suppo on Basecamp:

> Another approach could be banning the user instead of deleting it.

I had a test account "spam_test_account" so I made a post in the Forum part of the forum, and then banned it using my moderator power (banning done by Nick Gammon). 

Without changing any fields on the forum I hit the "Add" button to add the ban. I got this response:

![screenshot from 2015-02-17 06 42 04](https://cloud.githubusercontent.com/assets/185088/6218294/2659ec76-b671-11e4-8f01-73cca10e7b47.png)

But, I banned "spam_test_account", not me!

On my other computer I see also:

![screen shot 2015-02-17 at 6 40 58 am](https://cloud.githubusercontent.com/assets/185088/6218309/56e4b1dc-b671-11e4-8e68-739351ffa081.png)

OK, I see what probably happened. As I included "ban on IP" my IP address (which was the same for both users) got banned. 

This is a bit of a trap for testing. Please change so that you cannot accidentally ban our own IP address.

**Comment by matteosuppo** [comment]
Preventing the ban of the IP would invalidate the need for testing the feature. It's much better to test it with a way to regain access.
