### ISSUE TITLE
Spelling mistake on downloads page

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#178]
On this page: http://arduino.cc/en/Main/Software

The word "Upgrade" is misspelt:

![a56e4fc6567837af9742407b40a62d43](https://cloud.githubusercontent.com/assets/185088/6240653/6cb13d2e-b765-11e4-83d2-848cdd6bd136.png)

**Comment by mastrolinux** [comment]
Fixed few days ago. Thanks for reporting.
