### ISSUE TITLE
Someone is both God Member and Faraday Member at the same time

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#179]
![screenshot from 2015-02-20 10 32 29](https://cloud.githubusercontent.com/assets/185088/6278575/df1a9bda-b8eb-11e4-85fd-e77d6bea196b.png)

I thought you were one or the other.

**Comment by matteosuppo** [comment]
Technically one could be a member of multiple groups, but this is clearly not what you want. I'll check if this is a problem of configuration or a real bug in the software.

**Comment by nickgammon** [comment]
It isn't a group, it's a ranking. As you make posts you progress up a ranking level. Or if that statement is incorrect perhaps you can explain what these membership groups are all about?

**Comment by matteosuppo** [comment]
The software doesn't really distinguish from groups and rankings. In this case the primary group was assigned as God Member (and that's the case only for 2 members of the forum). 
I fixed it.
