### ISSUE TITLE
I want emails but not alerts

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#180]
If I want to subscribe to a thread I click on the button "Receive emails and alerts" here:

![screenshot from 2015-02-20 10 39 29](https://cloud.githubusercontent.com/assets/185088/6278684/fa4bc87e-b8ec-11e4-9481-b5e84b7aaef6.png)

However I just want an email, not an alert. That is not shown as an option, which is confusing.

Also, if I subscribe to a thread, to which I have **not** made a post, the "subscribed" icon (which looks like a pair of spectacles in the listing of threads) does not appear.

Also see: https://github.com/arduino/forum-issues/issues/170

**Comment by mastrolinux** [comment]
This should be in place, please verify!

**Comment by nickgammon** [comment]
When I click on "Receive Emails" the box above does indeed change to "Receive Emails". However if I exit that page and reload it, the box now reads "Receive Emails and Alerts". I'm not sure what I will receive, but the change doesn't seem to "stick".

**Comment by nickgammon** [comment]
However the "subscribe" icon (spectacles) does appear in the main listing.
