### ISSUE TITLE
Diplay of forum on Mobile devices

### ISSUE THREAD

**Issue by thepahtmaster** [arduino/forum-issues#183]
Hi there,

I am trying to acces the forum on my Android phone (Samsung GT S5360). 

I hav tried three differnt browsers and both mobile and desktop user agents. The forum displays one characther wide (horizontally). This makes each post a near infinite vertical line of characters.

Is there a "forum app" e.g tapatalk to use as a workaround?

Steve

**Comment by Chris--A** [comment]
Force a WAP/imode version and see how you go:
[http://forum.arduino.cc/index.php?wap2](http://forum.arduino.cc/index.php?wap2)
[http://forum.arduino.cc/index.php?wap](http://forum.arduino.cc/index.php?wap)
[http://forum.arduino.cc/index.php?imode](http://forum.arduino.cc/index.php?imode)

**Comment by matteosuppo** [comment]
Do you still have this problem? Can you provide a screenshot?

**Comment by thepahtmaster** [comment]
![sc20150113-222713](https://cloud.githubusercontent.com/assets/11314433/6684884/3bbe7230-cc8d-11e4-8105-46f810cbfee6.png)
![sc20150113-222814](https://cloud.githubusercontent.com/assets/11314433/6684900/5a613e02-cc8d-11e4-997a-257f349b90ab.png)
![sc20150113-222823](https://cloud.githubusercontent.com/assets/11314433/6684914/71ba6768-cc8d-11e4-96d3-01b48b969a7b.png)


Thanks both,

Forcing wap / imode is time consuming and not very elegant, however it's a very effective workaround.

I consider this (mostly) resolved,but attach screenshots for completeness (using Opera Mobile, results are the same wheter desktop or mobile usr agent).

**Comment by thepahtmaster** [comment]
Oops,

screenshots were upside down.

![sc20150317-095629](https://cloud.githubusercontent.com/assets/11314433/6685134/febe78c4-cc8e-11e4-9be9-50b0995fed08.png)
![sc20150317-095622](https://cloud.githubusercontent.com/assets/11314433/6685139/126cd942-cc8f-11e4-8ebc-1423564aa011.png)
![sc20150317-095615](https://cloud.githubusercontent.com/assets/11314433/6685152/2ccf0404-cc8f-11e4-82b6-c2572b9221e6.png)

**Comment by mastrolinux** [comment]
Let's use chrome or firefox on mobile, the website works with those browsers.
