### ISSUE TITLE
How to remove MERGED redirections?

### ISSUE THREAD

**Issue by RobTillaart** [arduino/forum-issues#186]
See papayacode here - http://forum.arduino.cc/index.php?board=18.0

**Comment by mastrolinux** [comment]
Looks like this issue is fixed in SMF master branch. @matteosuppo was trying to merge that branch in our code base but many other things were changed so we need to be extremely careful. Will deploy the fix on dev server during next week.

**Comment by RobTillaart** [comment]
WAY OLD
