### ISSUE TITLE
Cannot move to sub-forum

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#187]
A user made two posts (cross-posts). One was in Italiano, and the other in Italiano -> Hardware.

After a "report to moderator" I tried to merge the two threads. I can't merge directly because I (still) get this error:

![screenshot from 2015-04-01 07 49 08](https://cloud.githubusercontent.com/assets/185088/6929098/ec406020-d843-11e4-86e1-2d1e41640afe.png)

So until that is fixed, these days I first move the thread to the new forum section, and then merge them.

However when I tried to move one of the threads I see this:

![screenshot from 2015-04-01 07 45 30](https://cloud.githubusercontent.com/assets/185088/6929115/09431b86-d844-11e4-834e-a992238081b3.png)

You will note that there is no Italian section there at all.

However if I try to move something from another part of the forum, you can see all the Italian parts:

![screenshot from 2015-04-01 07 47 29](https://cloud.githubusercontent.com/assets/185088/6929126/1f8ce886-d844-11e4-8448-6fd18016b2c2.png)

I understand suppressing the exact sub-forum from the move (after all you don't want to move onto itself) but the other sub-forums should be available. Otherwise that thread can't be merged or moved at all (in the Italian section).

**Comment by nickgammon** [comment]
When is this going to be fixed? Someone now wants me to move a Spanish post into Spanish -> Documentation. I cannot.

**Comment by per1234** [comment]
Hi nickgammon. Thanks so much for reporting this bug! Since the moderation system has been completely changed by the switch to Discourse this week, this issue is now obsolete. If anyone does spot this problem happening again, please comment here and I'll reopen the issue.
