### ISSUE TITLE
report to moderator

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#190]
I've clicked that link to report a spam topic. I've left the text field empty and pressed "submit". Forum replied I had to describe the report. So I entered "spam", clicked "submit" again and forum said 

```
An Error Has Occurred
The last topic report from your IP was less than 20 seconds ago. Please try again later.
```

Ehm...

**Comment by per1234** [comment]
Hi ffissore. Thanks so much for reporting this bug. Since the forum system has been completely changed by the switch to Discourse, I'm going to guess this spurious rater limiting issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
