### ISSUE TITLE
Forum Profile settings disappear

### ISSUE THREAD

**Issue by per1234** [arduino/forum-issues#194]
Profile > Forum Settings > Settings > Forum Profile
I add a Website Title and Website URL and click Change Profile. The link appears as expected on my forum posts. A few hours later the links have disappeared and when I go back to the Forum Profile page the Website Title and Website URL fields are blank. I have repeated this process at least 5 times now with always the same result.

**Comment by ffissore** [comment]
Me too. Changed my profile yesterday. Today is back to its previous version. Notified devs via chat some months ago, still no fix @mastrolinux @matteosuppo

**Comment by per1234** [comment]
This issue went away during the big SSO shakeup of the forum.

I actually seem to remember reading a forum thread that said the behavior described in this issue was intentional so maybe the fix of the issue was unintentional.

I do understand the motivation behind not wanting to allow links in bios due to the benefits for spammers but having it mysteriously disappear after some hours instead of being disabled from the start was a terrible idea.

**Comment by BallscrewBob** [comment]
Can this be re-opened as the symptoms are exactly what I am currently experiencing

 http://forum.arduino.cc/index.php?topic=520411.new#new

Should not the feature be either fully on and working or fully off and deleted from all the profile pages not some random maybe/maybe not.

**Comment by SlashDevin** [comment]
Srsly, how did @per1234 get the link?  Maybe just transferred from the old forum SW?  I keep trying to add a link to NeoGPS et al, but it never sticks.  :(

**Comment by BallscrewBob** [comment]
It is not post count related.
Over 3,000 under my belt so hardly a spammer.
Going with old forum transfer but it clearly got broken.

**Comment by marcogarzotti** [comment]
Same issue here: https://forum.arduino.cc/index.php?topic=595795.0

**Comment by per1234** [comment]
This seems to no longer occur now that the forum software has been switched to Discourse this week. If anyone encounters this sort of problem again, please comment here and I'll reopen. I'll be sure to keep an eye out for it as well.
