### ISSUE TITLE
Throttling of posts causes genuine posters to lose their message

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#195]
See this thread: http://forum.arduino.cc/index.php?topic=353086.0

A user with a low post count replied to a question and was told: 

> You have exceeded the number of posts you can make in a 10 minute period.

So far, so good, the throttling is working. But ...

A genuine poster has now lost his/her **entire post**! Can't this be a warning message, with the post intact, like it is if you exceed the maximum number of characters in a post? That way they can wait 10 minutes and try again, and not lose their typing.

Not echoing what they entered doesn't really slow spammers down, because they will be copying and pasting anyway.

**Comment by mastrolinux** [comment]
Nicks suggests that the throttling should not apply to people who:

* Joined more than 1 month ago
* Have made more than 10 or 20 posts, especially if the first post is over 24 hours old.

**Comment by RobTillaart** [comment]
Agree with Nick, and if it not works we can change it later

**Comment by nickgammon** [comment]
In any event, you should **not lose what you posted**. A spammer won't care (they will just hit a hotkey to reproduce the spam). and a genuine new forum member, who is trying to be helpful and respond to questions, will be pissed off.

**Comment by nickgammon** [comment]
This was reported on 19th October 2015, and is regarded by you guys as a critical bug. When is something going to be done about it?

**Comment by per1234** [comment]
The Discourse software the forum was switched to using this week does preserve the user's post when they are blocked from posting due to rate limiting.
