### ISSUE TITLE
looking a discussion make it appear multiple time in updated topic

### ISSUE THREAD

**Issue by MauroMombelli** [arduino/forum-issues#196]
i just look at a multiple-page discussion and now it appear in my "update topic" page, if i click i land into the page 2, then it appear again and send me to page 2 etc...

as this discussion has 9 page is pretty annoing. It is not the first time, this time i keep it there so you can have a look; the discussion is "Cheap-Thermocam V3 | A cheap thermographic camera for everyone !" and my username is "lesto".

have a nice bug-hunt

**Comment by per1234** [comment]
Hi @MauroMombelli. Thanks so much for reporting this bug. Since the forum system has been completely changed by the switch to Discourse, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
