### ISSUE TITLE
Quick Reply, Line height 

### ISSUE THREAD

**Issue by 00alis** [arduino/forum-issues#200]
Line height is too little, it should be al least normal

<img width="992" alt="screenshot 2015-12-07 10 57 44" src="https://cloud.githubusercontent.com/assets/6151328/11715114/a2fca25c-9f3f-11e5-8f53-0d43f80eb538.png">
<img width="992" alt="screenshot 2015-12-07 11 00 26" src="https://cloud.githubusercontent.com/assets/6151328/11715116/a5a461ac-9f3f-11e5-9f50-dec22f575b75.png">

**Comment by per1234** [comment]
Closing as fixed by the switch to the Discourse forum this week. Thanks 00alis!
