### ISSUE TITLE
Attaching images

### ISSUE THREAD

**Issue by 00alis** [arduino/forum-issues#201]
It would be really helpful to have images in line or at least thumbnails into posts https://basecamp.com/2546761/projects/6328288/messages/51748301

Right now it is really hard to see that there is an attachment at all.

Also it is not possible to add attachment from the Quick Reply form, could we add it?

**Comment by alexceltare2** [comment]
How is this issue not fixed yet?

**Comment by BallscrewBob** [comment]
This issue I think can be closed with the recent auto insert feature for pictures

**Comment by per1234** [comment]
>It would be really helpful to have images in line

I agree with BallscrewBob that the auto image embedding feature resolves this functionality that for so long was only achievable through some obscure forum gymnastics.

>Also it is not possible to add attachment from the Quick Reply form, could we add it?

That was also very annoying and would have been nice if it had been fixed back in 2015. However, it's now 2021 and we have a shiny new forum that doesn't have such thing as "Quick Reply", so this part of the feature request is now obsolete.
