### ISSUE TITLE
Redesign Notification dropdown

### ISSUE THREAD

**Issue by 00alis** [arduino/forum-issues#202]
it is really broken: you cannot see what option you have selected (needs a checkmark by the selected option), it is not clear that is a dropdown either.

<img width="396" alt="screenshot 2015-12-07 11 07 40" src="https://cloud.githubusercontent.com/assets/6151328/11715152/f7513b9c-9f3f-11e5-98ff-4c4c47a4259f.png">
<img width="379" alt="screenshot 2015-12-07 11 09 43" src="https://cloud.githubusercontent.com/assets/6151328/11715154/f988b3cc-9f3f-11e5-8ba1-3d6d980184fc.png">

**Comment by 00alis** [comment]
here it is how it should look like with the dropdown arrow and the check on the selected option

![screenshot 2015-12-11 17 41 11](https://cloud.githubusercontent.com/assets/6151328/11749529/9da231ec-a02e-11e5-92e0-d49c9901dadd.png)

**Comment by 00alis** [comment]
@samura

**Comment by 00alis** [comment]
Check asset in svg: https://drive.google.com/file/d/0B_6MhyhSmjXeVFo4SlQ2MW1yMVE/view?usp=sharing

**Comment by samura** [comment]
Waiting for merge.
