### ISSUE TITLE
Turn 'Quote' and 'Quick Edit' into buttons

### ISSUE THREAD

**Issue by 00alis** [arduino/forum-issues#203]
Right now they don't look like buttons. Also 'More' should be moved further apart from 'Quick Edit' cause now they seem the same thing.

<img width="229" alt="screenshot 2015-12-07 11 21 51" src="https://cloud.githubusercontent.com/assets/6151328/11715175/22ffd1f4-9f40-11e5-9eff-384d7ca2b6ac.png">

**Comment by per1234** [comment]
Thanks @00alis. I agree that would have been a nice improvement to the UI.

After the switch to Discourse, there is no longer a "Quick Edit" functionality, and quoting works very differently, and also does have a reasonably "button looking" button. So I'm going to close this issue as obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
