### ISSUE TITLE
Column spacing and line height

### ISSUE THREAD

**Issue by 00alis** [arduino/forum-issues#204]
![screenshot 2015-12-10 13 08 20](https://cloud.githubusercontent.com/assets/6151328/11715223/60a47bb8-9f40-11e5-9f31-38270d8fec54.png)

We should reduce the column dimension and increase the  line height

**Comment by per1234** [comment]
Since the layout has been completely changed by the switch to Discourse, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
