### ISSUE TITLE
Google search results on the forum are not useful

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#209]
I tried to search the forum using Google for the word "auction". I'm sorry I can't attach a link to the image on GitHub because when I try, I get the error message "Something went really wrong, and we can’t process that file.". I tried JPG and PNG and it still didn't work. If you Google for:

> github "Something went really wrong"

You get over 2000 matches.

---

Anyway, this is the result, with images hosted on my own web site:

![Google search results](http://gammon.com.au/images/Arduino/Arduino_forum_WML_search_results.png)

What is WML? I opened a forum thread about this: http://forum.arduino.cc/index.php?topic=385603

The opinion there is that this is something to do with the **;wap** on the end of the URL. 

Anyway, if I try to open one of those links, because I might want to get help from the forum, I see this:

![Open WML link](http://gammon.com.au/images/Arduino/Arduino_forum_WML_search_results2.png)

No forum page opens. Now if I try to actually download the file and open it I see this:

![Open WML link](http://gammon.com.au/images/Arduino/Arduino_forum_WML_search_results3.png)

---

This is truly hopeless. The links served up by Google are useless to people using a desktop computer. And the reason must be at the forum end. You _should not_ be allowing _;wap_ files to be indexed by Google. Put an entry in robots.txt or something.

The whole point of a forum - especially for beginners - is that you can search it. And don't tell me to use the forum search, because that just redirects to Google anyway.

This doesn't happen to every search term, but often enough, when I search for something, I get this "wap" at the end of the URL.

**Comment by RobTillaart** [comment]
think It should add some filters like this

auction site:arduino.cc -wap2 -imode

**Comment by nickgammon** [comment]
That seems to help. What does -imode do? I can't see any reference to it. 

However people who are searching "in the raw" with Google (not using the search bar) won't think to type those words in.

**Comment by RobTillaart** [comment]
in google search the - sign works as a "not" filter The + sign tells it must be in  (default)
If you want to search for beer and not heineken ==> +beer -heineken

**Comment by nickgammon** [comment]
OK, well what is "imode"? I know we don't want **wap**, is **imode** something we also don't want?

**Comment by nickgammon** [comment]
In any event, I think that the robots.txt file should tell Google to not bother indexing those "wap" pages.

**Comment by BallscrewBob** [comment]
This can probably be closed with the new search having been implemented
