### ISSUE TITLE
Re-enable images and links in the signature.

### ISSUE THREAD

**Issue by Chris--A** [arduino/forum-issues#210]
A lot of people have useful links in their signature, which I had until today. I edited a certain part of my profile and these bbc tags were stripped.

You have the option in the profile settings for users to disable viewing peoples signatures, so if someone doesn't like them, they can get rid of them.

No need to make the wider community suffer because of a few grumpy people.

At least allow images and links that reside on the forum.arduino.cc domain.

**Comment by Chris--A** [comment]
@00alis 

And what makes matters worse, the profile setting I changed has reverted back, similar to what is causing the issues here: https://github.com/arduino/forum-issues/issues/205#issuecomment-219583548

**Comment by 00alis** [comment]
This was not a design decision, but a technical issue, please refer to @mastrolinux for these kind of problems, thanks!

**Comment by Chris--A** [comment]
Any word on this?

I'll re-iterate: users can disable forum signatures if they please. A majority of people do not care about links, images or even verbose over-the-top sigs. It is common place on public communities.

For sure there needs to be guidelines, however, please be encouraged to do what the community wants, not what a minority of moderators expect. And it is clear the community wanted customizable signatures, because we were using them before an odd few decided it was *bad*.

**Comment by mastrolinux** [comment]
hi @Chris--A that feature was abused by some users and a lot of spammers, we disabled it for security reasons.

**Comment by BallscrewBob** [comment]
Hi @Luca so this can be closed too ?

**Comment by per1234** [comment]
Signatures are intentionally not supported natively by the Discourse software now used by the Arduino Forum:
https://meta.discourse.org/t/automated-signatures/1127
Since the forum now has no capacity for signatures, I'll close this as obsolete.
