### ISSUE TITLE
"Moved" notification has {UNSUBSCRIBELINK} in it

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#211]
I got a message today from webmaster@arduino.cc as follows:

```
A topic you are watching has been moved to another board by AWOL.

View the topic at: http://forum.arduino.cc/index.php?topic=403079.new#new

Unsubscribe to this topic by using this link: 
{UNSUBSCRIBELINK}

Regards,
The Arduino Forum Team.
```

I presume "{UNSUBSCRIBELINK}" should expand out to something.

**Comment by nickgammon** [comment]
Is this hard to fix? It's been 17 days. I got another such notification today.

**Comment by nickgammon** [comment]
It's been three months and I still get such notifications.

**Comment by per1234** [comment]
Closing as obsolete because the new Discourse-based forum does not send emails on moved watched thread.

**Comment by sterretjeToo** [comment]
> Closing as obsolete because the new Discourse-based forum does not send emails on moved watched thread.

Did you forget to close it ?
