### ISSUE TITLE
 a blue transparent screen

### ISSUE THREAD

**Issue by alengso** [arduino/forum-issues#212]
Hallo,
I am a newbie in Arduino, i have tried a blink for the first time and lucked, then i tyr to change a number a delay and luck too. But the last time I got a blue transparent screen in my sketch and can not write or change the number or anything on sketch.
I have tried  a new installed, but came the same problem.
I don't know to fix it , may be some can help me ?
thanks before.

alengso

**Comment by samura** [comment]
This is a project to report forum issues. This is not a forum issue. Please post your question at https://forum.arduino.cc
