### ISSUE TITLE
Just sign in and ban...

### ISSUE THREAD

**Issue by sachast** [arduino/forum-issues#214]
Hello, 

I just create an account on the Arduino Forum, i was writing my topic and when i tried to post it i have this message : 

> "Sorry sachast, you are banned from using this forum!
> spam
> This ban is not set to expire.

I never post nothing, i don't understand why i'm banned... 
Someone can help me ? 

Have a nice day, 

Sachast 

ps : sorry for my bad english i speak french...

**Comment by per1234** [comment]
Hi @sachast. I'm sorry that this happened to you and that you didn't receive any response here about it. If you never were able to resolve the issue, please try again now. There was a major reworking of the Arduino Forum this week, which most likely resolved this issue. If you still can't get in, please comment here and I'll try to help you out.
