### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by sterretje** [arduino/forum-issues#216]
Since this morning (SA time), forum slow and occasionally 504 gateway timeout messages :-(

See http://forum.arduino.cc/index.php?topic=427488.0

**Comment by sterretje** [comment]
And now it's "bingo". Every attempt to access the forum results in 504.

**Comment by TerryKing** [comment]
Lots of 502 and SLOOWWW 7pm EST + 25 October 2016

**Comment by sterretje** [comment]
Just got a single 502 bad gateway again; forum did feel slow (reported another issue that I had to submit reply 3 times.
