### ISSUE TITLE
SMF database error and needed multiple attempts to post

### ISSUE THREAD

**Issue by sterretje** [arduino/forum-issues#217]
I think that it was yesterday or the day before that there was a glitch and I got an error message regarding "SMF and database". It solved itself quickly, sorry that I don't have an exact time and message.

This morning (approax 06:15 am South African time) it took three attempts to post a reply. The first time I ended up (after a while) on the page to post a new topic, the second time it got stuck 'verifying the id' (no automatic redirect; again after a while) and the third time it succeeded (reply #3 in http://forum.arduino.cc/index.php?topic=446174.0)

Just reporting, I know that those vague descriptions do not really help).

**Comment by sterretje** [comment]
Never mind (ashamed)

The latter part was a local network issue on one of my three networks. Reset router solved the issue.

I apologize.

**Comment by sterretje** [comment]
Never mind (a bit ashamed)

Rebooted network router and cleared firefox's cache and second problem now seems to be solved.

Sorry for the inconvenience.

**Comment by sterretje** [comment]
Hmm

spoke too early. Other network (cellphone, both 4G and WiFi) and it's still slow at occasion. This is posted from my normal laptop (different WiFi / ISP network) and github (or other sites) don't seem to give slow performance.

**Comment by sterretje** [comment]
I actually felt this coming; just got a 502 bad gateway.

**Comment by adamdavsi** [comment]
For the process of the Wifi settings and all and that you can easily set the entire process for that, you can also check the entire settings from the help of the [Google Drive tech help](https://googlesupport.co/google-drive-support/) for the entire process to know that settings for that.

**Comment by per1234** [comment]
@smellai (or any other admin) please delete adamdavsi's spam comment. I have also reported them to GitHub.

**Comment by sam13th** [comment]
Hey, I've come across the same error a few days back and it is a common database error recently so I've enlisted it in my [facebook](url=https://www.facebook.com) page you can check that out from there if you want to. Hope that will be helpful to you.

**Comment by PeterAlberto** [comment]
I just verified my account and it was smooth. If those errors come, you just need to retry and things will be okay again. Try closing the internet connection from the [router](https://www.facebook.com) and then reconnect.
