### ISSUE TITLE
Website slow

### ISSUE THREAD

**Issue by sterretje** [arduino/forum-issues#218]
The website is slow (again); takes between 20 and 30 seconds to load a page. Sometimes it's fast.

http://forum.arduino.cc/index.php?api&pm&callback=unreadpm&callback=jQuery111002576620285874871_1483671688741&_=1483671688742 takes anywhere between 10 and 25 seconds (checked 3 times).

See [http://forum.arduino.cc/index.php?topic=427488.msg3070539#msg3070539](url)

Win8, Firefox 50.1.0
05:12 South African time

**Comment by rpt007** [comment]
Confirmed.
IPad displays corrupt pages, especially the top part of a site us doubled and behaves strangely when trying to scroll down. Valid for browsers Chrome and Safari.

rpt007

**Comment by sterretje** [comment]
Seems to be OK now on my side since a number of hours after I reported initially; some feedback would be nice from the webmaster that it is (temporarily?) fixed would be nice ;)

**Comment by rpt007** [comment]
Responsiveness - yes (as long as it lasts …)
But: look at the screen of my iPad, no matter if I use Chrome or Safari:
