### ISSUE TITLE
Email notifications are sent for thread posts previous to the subscribe time

### ISSUE THREAD

**Issue by per1234** [arduino/forum-issues#219]
Some time after choosing to receive emails for a thread or being subscribed by replying on the thread I receive emails for every post on that thread, including ones posted previous to the time I subscribed to the thread. This is very annoying (especially with long threads) to the user and wasteful of Arduino's bandwidth. This behavior began maybe 6 months ago. Before that time emails were only sent for new posts on the subscribed thread.

**Comment by per1234** [comment]
@mastrolinux please look into this issue.

**Comment by BallscrewBob** [comment]
Hi Per.
Can this be closed ?

**Comment by per1234** [comment]
I haven't experienced this issue for some time, whereas at the time I made this report it happened for every subscribe, so I do think it has been fixed.
