### ISSUE TITLE
Bad directory tree

### ISSUE THREAD

**Issue by Blade2021** [arduino/forum-issues#224]
I'm getting "File not found" on many of the links connected to the navigation bar. 

Including but not limited to:
Tutorial Page - https://www.arduino.cc/en/Tutorial/HomePage
Reference Page - http://www.arduino.cc/en/Reference/HomePage
Education - https://www.arduino.cc/en/Main/Education

aka anything listed under domain: https://www.arduino.cc/en/*

**Comment by smellai** [comment]
Hi @Blade2021 we are trying to solve this https://github.com/arduino/forum-issues/issues/223
sorry about that

**Comment by Blade2021** [comment]
@smellai Ok, Not a problem, just wanted to make sure it was known.
Thanks
