### ISSUE TITLE
Old forum links broken

### ISSUE THREAD

**Issue by Coding-Badly** [arduino/forum-issues#226]
http://forum.arduino.cc/index.php?topic=14908.msg109523#msg109523

...has a link that leads to this...

Warning: mysqli::mysqli(): (42000/1044): Access denied for user 'forum'@'%' to database 'forumwrap' in /var/www/forum/old_forum_hijack.php on line 16
Connect failed: Access denied for user 'forum'@'%' to database 'forumwrap'

**Comment by Serjlee** [comment]
This happened in a short time window while we were working on security measures, and it is now fixed.
