### ISSUE TITLE
Arduino Uno R3

### ISSUE THREAD

**Issue by maddy2610** [arduino/forum-issues#227]
I am working on an Arduino Uno R3 which i had bought from  http://www.w11stop.com/ard-uino  . I wanted to have the ability of controlling the Arduino wirelessly, like stopping the Arduino without having to pull the power-plug every time. Is it possible?

**Comment by Coding-Badly** [comment]
The forum...
[http://forum.arduino.cc/index.php?topic=471126.0](http://forum.arduino.cc/index.php?topic=471126.0)
...is the appropriate place for your question.
