### ISSUE TITLE
New forum members with no user names

### ISSUE THREAD

**Issue by per1234** [arduino/forum-issues#228]
We are seeing some new forum users who have no user name recently. I just asked [one of them](http://forum.arduino.cc/index.php?action=profile;u=730933) about it and they said they signed up as "SanderM2001" but now the forum doesn't show their name:
http://forum.arduino.cc/index.php?topic=471644.msg3227796#msg3227796
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/25219153/44a911fe-2562-11e7-824f-a1f16f313ed0.png)

Other examples of "no-name" users:
http://forum.arduino.cc/index.php?action=profile;u=725310
http://forum.arduino.cc/index.php?action=profile;u=729745

Forum thread for this issue:
http://forum.arduino.cc/index.php?topic=471161
 
UPDATE: The user name SanderM2001 now appears but still no user name for the other two.

**Comment by Serjlee** [comment]
The issue was identified and fixed. Thank you!

**Comment by per1234** [comment]
@Serjlee it seems this issue or a similar one is back. Here is a user profile with no name:
http://forum.arduino.cc/index.php?action=profile;u=39119
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/26230150/a66f5808-3bfb-11e7-8afa-2e014ccf6205.png)

Some other users also reported the same thing happening to them today:
http://forum.arduino.cc/index.php?topic=478235
but in their case the issue has gone away already.

**Comment by Serjlee** [comment]
This user was unique and actually had an empty username, (and not simply an empty displayname) and it was like this since 2011.

Thank you for noticing us, as it was causing that weird issue described in the topic you linked.
