### ISSUE TITLE
New forum 'software': issues

### ISSUE THREAD

**Issue by sterretje** [arduino/forum-issues#229]
Noticed a new forum 'software' yesterday.

Using Firefox 53 on Windows 8, the select button in the code window does not work. First reported [http://forum.arduino.cc/index.php?topic=473506.msg3238654#msg3238654]

**Comment by IamFof** [comment]
I am using Firefox 53 on Win10. and I have noticed that the "NEW" tags are totally missing on some boards and very sparse on others.

**Comment by sterretje** [comment]
Reply timeout seems to have been shortened. When submitting a quick reply (that was not that quick to type in), I often end up on a page to start a new thread.

In the past I had this once in a while, with the new forum 'software' I have had it several times already.

**Comment by per1234** [comment]
> When submitting a quick reply (that was not that quick to type in), I often end up on a page to start a new thread.

I've also had this happen a couple of times on forum thread replies and a similar experience in a private message since the website change. I lost all or most of the text I had written.

**Comment by per1234** [comment]
I have opened a new issue for the lost replies problem. Lets make this issue only be about the "select" button on code blocks not working and create a separate issue report for each other bug. This will make it easier to track each issue and avoid any slipping through the cracks. I'd appreciate if @sterretje or an admin would change the title of this issue to reflect that. @IamFof please open a new issue for the "NEW" tags bug.

**Comment by IamFof** [comment]
@per1234 
New issue, "Missing "NEW" tags", opened.

Fof

**Comment by per1234** [comment]
@Serjlee @mastrolinux @matteosuppo @smellai over a month later and the code box select button on the forum is still broken. It worked fine before you made all those changes to the website. Please look into this.

**Comment by Serjlee** [comment]
The issue was unrelated to previous forum changes, but was due to the way SMF handled the "select" button, broken on Firefox 53+

Now it should be fixed.

**Comment by per1234** [comment]
Working for me now. Thanks!
