### ISSUE TITLE
Replies to threads are sometimes lost

### ISSUE THREAD

**Issue by per1234** [arduino/forum-issues#231]
This was previously reported at https://github.com/arduino/forum-issues/issues/229#issuecomment-298145047 but I'm opening a dedicated issue for it because I think it will be problematic to have a bunch of different bugs reported in one issue.

Ever since the forum was updated 2017-04-27 I have had repeated occurrences of replies being lost. This has happened on public forum threads as well as private messages. There have been multiple other reports of this bug:

https://github.com/arduino/forum-issues/issues/229#issuecomment-298145047
http://forum.arduino.cc/index.php?topic=473506.msg3238495#msg3238495
http://forum.arduino.cc/index.php?topic=473506.msg3241387#msg3241387
http://forum.arduino.cc/index.php?topic=473506.msg3241425#msg3241425
http://forum.arduino.cc/index.php?topic=473506.msg3241472#msg3241472
http://forum.arduino.cc/index.php?topic=473506.msg3245483#msg3245483
http://forum.arduino.cc/index.php?topic=473506.msg3246287#msg3246287
http://forum.arduino.cc/index.php?topic=473506.msg3246304#msg3246304

This is a big problem because we may spend a significant amount of time writing a reply, in fact it seems to be more likely to happen with long replies. Sometimes you can recover it from drafts but usually part has to be rewritten.

**Comment by per1234** [comment]
This is still happening...
Please fix this problem ASAP. These changes have drastically reduced the usability of the forum.

**Comment by BallscrewBob** [comment]
Confirming the issue.
Just lost a reply and ended up being logged out of the system after hitting POST.
Drafts folder did not have anything relevant in it so probably not going to re-do another reply.
Curious as to why SSO would affect replies ?

**Comment by per1234** [comment]
Still happening....
@mastrolinux @matteosuppo @smellai please look into this.

**Comment by per1234** [comment]
It just happened again. Please fix this!!!!!!!!!!!!

**Comment by Serjlee** [comment]
Did this still happened in the last couple of days?

**Comment by per1234** [comment]
It hasn't happened for me and I asked on the forum a few hours ago if anyone else had experienced it in the last couple days, Two people have replied to say they haven't had the problem and nobody has reported it happening. It looks like it is fixed. Thanks!

**Comment by Serjlee** [comment]
Yeah, it should be fixed! :)

Thanks for the feedback.

**Comment by 00alis** [comment]
This just happended to me now, lost the post and got redirected to the SSO. Just keeping this in check as it might be related to cache.

**Comment by Serjlee** [comment]
If you were asked to re-authenticate on the SSO the issue was very likely related to the SSO itself, as there is still some behind-the-scenes work in progress. 

Keeping this open, for now, just in case it happens to more people
