### ISSUE TITLE
Missing "NEW" tags

### ISSUE THREAD

**Issue by IamFof** [arduino/forum-issues#232]
Prior to the update, very occasionally, the "NEW" tags didn't show.
Since the update, they fail to show, more often. Today "Science and Measurement" & "Storage" have virtually none. that includes threads I know I have'nt read.
Not an earth stopper, but annoying.

Fof

**Comment by Serjlee** [comment]
Some time ago we did a database cleanup, which might have helped with this issue. Does this still happen to you?

**Comment by IamFof** [comment]
Hi Luca

Thanks for the feedback.  Always welcome.

This issue appears to have gone away, thankfully.

I do notice other little gremlins, that come and go,  eg yesterday for a
short while, I kept getting passed to the index page when I pressed a tab.
After restarting the forum, all was good again.

Please pass the thanks of all the forum users for your work.  I would ask,
on behalf of all the members, if the IT team would post messages to keep
the members informed of issues, and what is happening.

Regards

Fof

**Comment by Serjlee** [comment]
Hey, your thanks were much appreciated!

We have lots of websites to manage, and most of the time we are too busy catching those gremlins to properly inform the community about the work in progress, so we do it when we can.

This repo has a fairly big backlog of open issues (with many outdated ones), but please continue to report them here, as it's the quicker way to reach us.

**Comment by Serjlee** [comment]
Closing the issue now, feel free to re-open it if it ever re-occours.
