### ISSUE TITLE
Wrong location from email links

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#235]
A new issue seems to have arisen from the forum change,

If I follow a link back from an email in which I have been "quoted" it drops me off at the top of the forum and not in the section of the forum or even at the topic in which the quote originated.

This can happen for up to 4 times using the same link and then suddenly that link may take you to the actual topic and work as intended. 
Quite hard to reproduce unless you are the "quoted" recipient.

**Comment by Serjlee** [comment]
Can you paste me the link you received?

**Comment by BallscrewBob** [comment]
[](http://forum.arduino.cc/index.php?msg=3248287)

As I said above after a few attempts it becomes a valid link to the actual source thread.
per1234 has also seen this action as mentioned here[]( http://forum.arduino.cc/index.php?topic=473506.msg3248287#msg3248287)

**Comment by Serjlee** [comment]
Ok I was able to identify the issue. Will be fixed soon.

Thank you!
