### ISSUE TITLE
Can't log in to the forum after authenticating on id.arduino.cc

### ISSUE THREAD

**Issue by marcelloromani** [arduino/forum-issues#238]
How to reproduce:

* Visit to https://id.arduino.cc
* Log in successfully
* Visit forum.arduino.cc : The "Sign in" option appears in the top right part of the page
* Try to log in clicking on "Sign in"
* Error: username or password are incorrect.

**Comment by smellai** [comment]
That should be fixed now, if you can't login with your account please reset your password and try again
