### ISSUE TITLE
Namespace over run

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#239]
Noticing a few more of these and whilst not critical they do look very messy.

[https://forum.arduino.cc/index.php?board=109.0](url)
![forum name over run](https://cloud.githubusercontent.com/assets/8212730/26034812/5807f512-3890-11e7-80ac-269ed63505c0.jpg)

**Comment by BallscrewBob** [comment]
Expanding this to include email names as user names as that seems to be the cause.
Email names still turning up as user names in the forum.

**Comment by BallscrewBob** [comment]
https://forum.arduino.cc/index.php?topic=482194.0

An ongoing issue it seems.

**Comment by smellai** [comment]
emails are not accepted anymore as username in signup form, problem will persist for old users that registered with email as username
