### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by sterretje** [arduino/forum-issues#241]
It seems to be back. 15:00 South African time. Tested on two independent internet connections.

Not sure if I needed to open a new issue or add to issue #216; hence a new one.

**Comment by sterretje** [comment]
Maybe spoke too soon; seems solved.

**Comment by BallscrewBob** [comment]
Yes cleared up here too. so probably mark as closed.

**Comment by Serjlee** [comment]
Creating a new issue was a good idea, as this one was completely unrelated.

It was an hiccup of the SSO, re-open this issue if it happens again.
