### ISSUE TITLE
SSO Login screen reveals password

### ISSUE THREAD

**Issue by sterretje** [arduino/forum-issues#244]
This might be a browser bug, I don't know.

Arduino forum login form (https://auth.arduino.cc/login?challenge=.......)

Type the first character of your password; as a proper password field, it shows *.
Click the little eye at the right of that field
Type the next character (does not have to be correct). Use backspace and a dropdown shows which reveals the complete password.

Tested on
Win7 64 bit with Firefox 53.0.3 (32 bit)
Android 6.0.0 with Chrome 58.0.3029.83

**Comment by BallscrewBob** [comment]
Cannot reproduce on FF (x64) under win 7 (x64)
Nor Chrome (x64) under same OS.

**Comment by sterretje** [comment]
Why is this now closed? Issue still persists.

**Comment by smellai** [comment]
I'll let you know as soon as it is online, I think later today

**Comment by smellai** [comment]
Could you please try now? Thanks

**Comment by BallscrewBob** [comment]
Sorry but not fixed yet SS to follow on slack.

**Comment by sterretje** [comment]
Seems to be solved for Windows 8 / Firefox 53.0.3 (32 bit). I will try later on my Android device.
