### ISSUE TITLE
Website spoofed

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#246]
"https://id.arduino.cc/optimumnutrition"

You have been spoofed pretty well

**Comment by Serjlee** [comment]
Well it's just a malicious user profile, like this one:
https://id.arduino.cc/ballscrewbob

Maybe we could make it more obvious it's just a user profile?

**Comment by BallscrewBob** [comment]
Maybe a good idea...
Also a good idea to kill that profile with fire.

**Comment by BallscrewBob** [comment]
Lets delete this thread if its ok with you.

**Comment by smellai** [comment]
Closing as opened in the other repository
