### ISSUE TITLE
Banned unfairly

### ISSUE THREAD

**Issue by alsaine** [arduino/forum-issues#248]
Hi,

I reported a moderator's spam post. He/she responded by indefinitely IP banning me in a way that entirely prevents me from viewing the forum.. and wrote

"Sorry atol_ikan, you are banned from using this forum!
Abuse of the report to moderator control. Take your toke, _and shove it_.
This ban is not set to expire."

How mature, moderator on a little power trip. Sorry to be a pest but I don't think this is fair, 

The posts did not abide by the rules found here:

https://forum.arduino.cc/index.php?topic=54857.0

Moderator name: AWOL

**Comment by alsaine** [comment]
How is it fair in any way that a moderator has the ability to permanently deprive users from access to a crucial resource that I would consider a valuable part of the cost of purchasing an Arduino? Yes obviously it is easy to use a VPN or change my IP, but the fact is that you have immature moderators who are acting as the unilateral arbiter or access to information. How ridiculous that they are allowed to prevent users from even reading the forums. And good to see absolutely no response on any channel from Arduino CC. Very disappointing but not surprising, obviously you are paying these moderators in power instead of in money.

**Comment by alsaine** [comment]
And even a cursory google search reveals the exact same moderator has done this exact thing before-- with no recourse available to the user, and no resolution from the admins and Arduino CC except unconditional support. Why bother having rules on the forums if the moderators don't have to follow them, and the users get banned for reporting those not following them?

**Comment by per1234** [comment]
In years of using the Arduino Forum daily I have never seen a post from AWOL that resembled spam. Are you sure that was the problem with the post you reported? If you could post a link to the post that you reported that could be helpful. I realize this is difficult since a ban prevents you from viewing the forum.

Regardless of whether the ban was justified, I do think it is wrong for banned users to be prevented from reading the forum. However, this issue has already been reported:
https://github.com/arduino/forum-issues/issues/177

**Comment by cryptocxeq** [comment]
What a joke! and #177 even funnier!
Did you try emailing support@arduino.cc? I bet you will never get a reply from Arduino, they don't put any money (?) / effort into their support or forums, so the support email never replies, and in the forums over time power structures and stupid childish stuff like this has propagated. This has been brought up multiple times in the dev discussion, the official forums, and on other communities, and they always seem to end up concluding that its worth the $ saving to abdicate all sovereignty to volunteers.

**Comment by mastrolinux** [comment]
@Serjlee we should allow viewing the forum to all banned users. In addition the IP ban should never be lifetime but a 6 months ban suffice.

**Comment by Serjlee** [comment]
@mastrolinux both of those are options already available for the forum moderators. I'm going to enforce them from now on.

**Comment by Serjlee** [comment]
All previous and future bans now always allow read-only access to the forum.
All IP bans are cleared after a set amount of days (180 right now).

**Comment by alsaine** [comment]
Why was this closed? Was the issue ever resolved? The power tripping moderator hasn't been mentioned at all. No action taken. No rule changes. No actual effort taken to resolve the cause of the problem? 

 Take your toke, and shove it.
 Take your toke, and shove it.
 Take your toke, and shove it.

**Comment by alsaine** [comment]
Meanwhile, I am still banned, and still with an offensive, derogatory, and immature ban message. Good work guys, you clearly resolved this issue.

**Comment by alsaine** [comment]
I never received any response from support@arduino
or from any of the other people I PMed, emailed, contacted, reached out to, etc.

What a joke.

**Comment by smellai** [comment]
Hi @alsaine, AWOL removed your ban

**Comment by alsaine** [comment]
I circumvented the ban almost immediately and I am now using a new account.
Think that it come to this is so sad and disgusting, All of this is so stupid! Thank powerful lord AWOL removed my lifetime IP ban This has been my favourite user experience
