### ISSUE TITLE
Avatars possibly broken

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#251]
It seems this issue is occurring again with some people reporting no avatars.
Myself included. My avatar shows in my profile but does not seem to have populated to your storage.

Also referencing this post in the forum

[http://forum.arduino.cc/index.php?topic=338609](url)

**Comment by Serjlee** [comment]
Yes, they were a bit broken. All new avatars are served via https, but SMF only supported external avatars served via http, hah.

Thanks for reporting it here.
