### ISSUE TITLE
Schematic for Nano missing

### ISSUE THREAD

**Issue by sterretje** [arduino/forum-issues#253]
Not sure if it belongs here or elsewhere. Following the link from the Nano product page (https://store.arduino.cc/arduino-nano) to the pdf of the schematic (http://download.arduino.org/products/NANO/Arduino%20Nano-Rev3.2-SCH.pdf) gives a 404 not found.

**Comment by per1234** [comment]
This sort of issue should be reported to https://github.com/arduino/Arduino/issues.

The arduino/forum-issues repository is only for reporting issues with the Arduino forum. Documentation or other website issues should be reported to arduino/Arduino or library documentation should be reported to the appropriate repository under https://github.com/arduino-libraries.

**Comment by mastrolinux** [comment]
So sorry about that. Just fixed! Please use the new URL written in the page.
