### ISSUE TITLE
Some threads are not HTTPS secure

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#254]
In some threads, for example: https://forum.arduino.cc/index.php?topic=498224.0 the post is marked as only partially secure, as you can see:

![arduino cc is not secure](https://user-images.githubusercontent.com/185088/31699197-5baf3628-b40d-11e7-9294-d63db4053737.png)

Judging by the page source, the avatars are served up as HTTP links, not HTTPS.

Whilst I don't think this particular issue is a major security threat, it looks bad if you see messages about the site not being secure, and if you get used to seeing them, you may not care if a more serious security issue happens to strike.

**Comment by smellai** [comment]
I think it's solved
