### ISSUE TITLE
A issue that only happens when using github.

### ISSUE THREAD

**Issue by CyrusMusic101** [arduino/forum-issues#255]
So I have been making a website and it works 100% the link to it is cyrusmusic.github.io

As you see there is the explore button. When using the github link it downloads the info.html, but not when I have it loaded up in my browser off my computer

Here is my a href

			<div class="container">
			<h1>Chs Robotics</h1>
			<a href="info.index" class="btn">Explore</a>
			</div>

 			<div class="footer">
  			<p class="ftm">© CHS Robotics: Developed by CyrusMusic101.</p>
			</div>

Is this issue on my end or yours?

**Comment by matteosuppo** [comment]
Hello, I'm not sure what's the problem and how it's related to our forum: cyrusmusic.github.io replies with 404

**Comment by Coding-Badly** [comment]
I smell spam.
