### ISSUE TITLE
up/down within threads

### ISSUE THREAD

**Issue by dougp2** [arduino/forum-issues#257]
Only a quibble.  When entering a thread I can use the up and down arrow keys to scroll through the thread but the Page Up/PageDown keys do not work until I left click somewhere on the page.  After that PgUp and PgDn work normally.

**Comment by per1234** [comment]
Hi @dougp2. Thanks so much for reporting this bug. I am not able to reproduce any longer with the new Discourse-based forum so I'm going to close this as fixed. If you are still having the problem with the forum, feel free to comment here and I'll reopen this.
