### ISSUE TITLE
Bogus error message when trying to edit a post within 5 minutes from posting

### ISSUE THREAD

**Issue by teo1978** [arduino/forum-issues#260]
Steps to reproduce:
- post a reply to a thread
- edit it
- save

Expected: should allow you to save. 

Observed: you get a bogus error message saying: 
> You have exceeded the number of posts you can make in a 5 minutes period. Please try again later.

There's no reason to impose a wait period between _edits_ (even between new posts it's pretty questionable, but I get the concerns about spam), and even if there was, the error message is clearly wrong.

I guess this is a bug in the mechanism that is supposed to prevent you from publishing a new post within the 5-minutes period.

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/forum-issues/issues/258

**Comment by KilianB** [comment]
And of https://github.com/arduino/forum-issues/issues/208

**Comment by Serjlee** [comment]
See https://github.com/arduino/forum-issues/issues/208#issuecomment-376096400
