### ISSUE TITLE
Please lock posts older than 12 months automatically.

### ISSUE THREAD

**Issue by RobTillaart** [arduino/forum-issues#263]
Would make my task as moderator a bit easier.

**Comment by per1234** [comment]
I don't like the prohibition some forums have against reviving old threads because I'd prefer to have all information on a specific topic collected in a single place rather than split into multiple threads.

There may be some exceptions where an old topic has become obsolete due to developments made since the last post in which case it would be better to start a new thread but I think that's a relatively rare occurrence.

I guess it would be helpful if you explained exactly how doing this would make it easier on the moderators.

**Comment by RobTillaart** [comment]
Today several new visitors have highjacked an old thread and asked for help. happens on daily basis, (especially when new school assignments are out ?)
The requests for help varied from just "HELP!" to a slightly better description.
I conclude that these posts are only loosely connected to the existing thread.
So I split off the new question from the old topic.
(sometimes I get a report sometimes I see them first)

If someone has a problem, he/she should describe it him/herself and add a reference to the old thread(s) as look alikes of his/her problem. Often old threads are solved (yes that is an assumption ) so if they have the same problem they could use the same solution. If the problem is different start your own thread.

Hijacking someone elses thread will still happen, but less. So as a moderator I need to split less threads on a day. That gives me more time to do fun stuff.

**Comment by RobTillaart** [comment]
Better make it posts older than 6 months

**Comment by RobTillaart** [comment]
and another one
![image](https://user-images.githubusercontent.com/462844/37157381-015f5766-22e9-11e8-93b0-491995a710dd.png)

**Comment by RobTillaart** [comment]
And another one
![image](https://user-images.githubusercontent.com/462844/37157620-9cdb6a7c-22e9-11e8-89b7-007f4ec8581f.png)

**Comment by RobTillaart** [comment]
sigh

**Comment by BallscrewBob** [comment]
Leave them open.
I have found info that has helped issues and its nice to be able to thank the originator and or add additional information.

Hijacks should be reported to mods (cough) and mods should simply split the hijack / spam / whatever.

**Comment by RobTillaart** [comment]
Splitting is not allways simple ... 
For me the simplest is just to leave it as it is,  because... why split it as it is related?

**Comment by BallscrewBob** [comment]
A lot of hijacks are not the same topic. But I agree that should it be relevant then leave it alone
