### ISSUE TITLE
Only main forum page available

### ISSUE THREAD

**Issue by dougp2** [arduino/forum-issues#267]
'View thread' link in email only goes to main page.

Also on main page, clicking on the top thread in a topic only goes to main page.

sample link: http://forum.arduino.cc/index.php?topic=540642.new#new

**Comment by per1234** [comment]
Same problem here, every forum page redirects me to https://forum.arduino.cc. The problem only occurs when I'm signed in to my Arduino account. If I'm signed out then I can view any forum page.

**Comment by dougp2** [comment]
Fixed it (apparently) by logging out then logging back in.

**Comment by sterretje** [comment]
Fixed by flushing the cache, cookies and all other crap that browsers store.

**Comment by per1234** [comment]
The problem was resolved for me around the time of dougp2's last comment, though I think their "logging out the logging back in" solution was purely coincidental since I had previously tried that many times without it helping and then the problem resolved itself without any action from me.

**Comment by BallscrewBob** [comment]
Happened again this morning.
Came in after a cache clean up to a fresh page and the sign in page just never appeared despite hitting the button. It just refreshed on to the forum page. Sorry but dont have any additional info.

**Comment by smellai** [comment]
It should be ok now, please re-open if it happens again
