### ISSUE TITLE
502 Bad Gateway / 504 Gateway Time-out

### ISSUE THREAD

**Issue by MarekBujko** [arduino/forum-issues#269]
502 Bad Gateway / 504 Gateway Time-out errors on forum page only now.

**Comment by sterretje** [comment]
Same issue at this moment.

Using two machines with different networks (mobile and work).

Cleared all browser history / cookies and it did not solve the issue.

**Comment by gdsports** [comment]
"504 Gateway Time-out" now

**Comment by tttapa** [comment]
Experiencing the same issue as well. For the last couple of hours, not once have I been able to reach the forum.

**Comment by MarekBujko** [comment]
Forum not work.

**Comment by sterretje** [comment]
Solved at this moment (14:45 South African time); approx. 8 hours down.

**Comment by sterretje** [comment]
One hour and fifteen minutes later and we have it again; not even going to bother with clearing cache.

**Comment by sterretje** [comment]
And fifteen minutes later it works again. For how long?
