### ISSUE TITLE
Timeouts and sso issue

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#273]
Initially  getting "gateway timeout" but after multiple attempts to get in and after passing through the SSO sign in I am still not signed into the forum.

Trying to open any of the sub forums just performs a refresh of the main list and does not jump to the sub forum chosen.

**Comment by sterretje** [comment]
Same here. Two different ISPs (using different modems).

Cleared cookies and cache. Signed in. After that, page still shows the sign-in in the right top but when you click it, you're taken back to the index page. So you're signed in but the system does not know it.

PS
The gatewate timeouts always seem to relate to hydra.

**Comment by BallscrewBob** [comment]
Seems to be slowly coming back up but some issues I think are in flux.
Looking like some form of migration ?
Got word they are on it.

**Comment by sterretje** [comment]
indeed, seems to be working again.
