### ISSUE TITLE
Spark, EMR, GLUE catalog Issue with redshift JDBC Jar

### ISSUE THREAD

**Issue by venkateshmora23** [arduino/forum-issues#276]
Hello, I am using pyspark to query data from redshift and also trying accessing Glue catalog from Spark. I am able to access separately Glue catalog in spark and Redshift in spark separately but when I want to use data from both sources in the same script. I am running into this issue 
pyspark.sql.utils.AnalysisException: u'java.lang.ExceptionInInitializerError: null;
after 
HiveUtils: Initializing HiveMetastoreConnection version 1.2.1 using Spark classes which is supposed to talk to Glue after this step. 
Below is the script I am trying to run :

from pyspark.sql import SparkSession
spark = SparkSession.builder\
.config("hive.metastore.client.factory.class", "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory")\
.getOrCreate();
spark.sql("show databases").show()
spark._jsc.hadoopConfiguration().set("fs.s3.awsAccessKeyId", "AK")
spark._jsc.hadoopConfiguration().set("fs.s3.awsSecretAccessKey", "SC")
query_k = """
select * from table limit 10 """
s3TempDir = "s3://path/"
jdbcURL = "jdbc:redshift://url?user=usr&password=pwd!"
df = spark.read.format("com.databricks.spark.redshift")\
.option("url", jdbcURL)\
.option("tempdir", s3TempDir)\
.option("query", query_k).load()
df.show()

I am triggering this using 
spark-submit --packages com.databricks:spark-redshift_2.10:0.5.2 --jars /usr/share/aws/redshift/jdbc/RedshiftJDBC41.jar,spark-redshift_2.10-2.0.0.jar,minimal-json-0.9.4.jar t1.py . ( I got the jars on my machine)

**Comment by smellai** [comment]
This repo is for tracking issue in the [site](https://forum.arduino.cc/) behavior. Closing
