### ISSUE TITLE
lots of random forum errors.

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#281]
[Just leaving the link back to the topic in the forum itself.](https://forum.arduino.cc/index.php?topic=682985.msg4601426#new)

**Comment by UKHeliBob** [comment]
Lots of problems with Alerts including multiple spurious alerts that vastly inflate the number displayed but don't actually exist

This is making spotting new posts that may need moderator action particularly difficult

**Comment by BallscrewBob** [comment]
We need some mitigation until any new software is in place as it seems to be spreading much wider than thought.

**Comment by BallscrewBob** [comment]
The ALERTS section next to the "Unread Posts" and "Updated Topics" needs to decrement properly.
It currently does not lower the count if you have read or dealt with the alert.

This means that if there are more than 5 (I think) then the only way to clear them is to "mark all as read" which means that some alerts will be dropped from view.

Both the "Unread Posts" and "Updated Topics" work just fine so there may be a clue or cue to be taken from that.
Fixing it may also help with the spurious "pop up" alert issue where some alerts (not all) are popping up more than once, usually in quick succession or maybe separated by a short (few second) pause.

**Comment by BallscrewBob** [comment]
The Alerts themselves can be VITAL to moderators in being able to respond in a timely manner so the dropping of unread ones is not a feature but a nasty little bug that means some issue may not get dealt with.

Moderators are spread around the globe but that comes with wide time differentials so another mod may not see the alerts for a a good few hours. 
This lost time could give spammers time to proliferate posts causing more work than is needed.

**Comment by supernova-ws** [comment]
According to https://forum.arduino.cc/index.php?topic=682985.msg4669205#msg4669205 this problem was resolved about Jul 08 2020. Is it true or problem still persists?

**Comment by BallscrewBob** [comment]
The problem still exists.

There are TWO types of ALERTS one is a pop up NOTIFICATION which you need to be signed up for.
The other is the ALERTS in the top bar of the forum.
Would you be the dev assigned by Luca ?

**Comment by BallscrewBob** [comment]
Closed as was almost completely mitigated by @supernova-ws .
