### ISSUE TITLE
Error 504 Ray ID: 594fdaa05b4d9736 • 2020-05-17 19:49:06 UTC Gateway time-out

### ISSUE THREAD

**Issue by StefanL38** [arduino/forum-issues#282]
Error 504 Ray ID: 594fdaa05b4d9736 • 2020-05-17 19:49:06 UTC Gateway time-out

maybe the experts can explain what makes a website like Arduino.cc getting errors gateway-Time-Out

too much requests at the same time? 
DDOS-hacker-attack?
some misconfiguration of the server slowing the server down?

**Comment by thomas990876** [comment]
I am getting the same problem

**Comment by hycminions** [comment]
Same here

**Comment by Ra-Pad** [comment]
I get the same error when trying to browse any page on "forum.arduino.cc". Ray ID is different though.
It shows my browser and Colombus Cloudflare are working, but it indicates that there is a host error.

**Comment by sterretjeToo** [comment]
Same here; had it yesterday evening once (approx 9 hours ago) and a refresh solved it.

Currently 3 attempts failed. Latest attempt:

Error 504 Ray ID: xxxxxxxxxxxxxxxx • 2020-05-18 03:47:55 UTC
Gateway time-out
You
Browser
Working
Johannesburg
Cloudflare
Working
forum.arduino.cc
Host
Error
What happened?

The web server reported a gateway time-out error.
What can I do?

Please try again in a few minutes.

Cloudflare Ray ID: xxxxxxxxxxxxxxxx • Your IP: aa.bbb.ccc.dd • Performance & security by Cloudflare

**Comment by sterretjeToo** [comment]
Seems OK now.

**Comment by StefanL38** [comment]
I can confirm this  website is working again.
Thanks
