### ISSUE TITLE
Can't quote a specific post

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/forum-issues#283]
Thread https://forum.arduino.cc/index.php?topic=685889

I can't quote the first message
quote link: https://forum.arduino.cc/index.php?action=post;quote=4613194;topic=685889.0;last_msg=4613424

I can quote the other two messages that are currently there.

**Comment by BallscrewBob** [comment]
Confirm sterretjeToo issue.
May be down to how the OP posted his code and all the other random issues in the forum.
Two other messages not showing in that post though.

**Comment by sterretjeToo** [comment]
From memory, there was something with those messages. I think the one was unrelated and I commented on that; as a result both disappeared (possibly moderator action but you (bsb) have better insight in that ;-))

**Comment by BallscrewBob** [comment]
Not my actions and the logs are a pain to trawl through as there are not enough filters to drill down to specific areas / topics etc. :(

**Comment by supernova-ws** [comment]
Can't confirm: https://forum.arduino.cc/index.php?topic=685889.msg4718353#msg4718353
Works in Chrome, W10.
What browser/OS you using? Did you try it in Incognito/Private mode? Some addons can interfere with forum code.

**Comment by BallscrewBob** [comment]
Win 7 x64 pro, chrome or edge chrome or ff.
This was the rare but special character bug so can be closed I think if sterretjeToo is in agreement.

**Comment by sterretjeToo** [comment]
Win10, Firefox 80.0.1

Installed ABP
Installed noscript;
following is blocked
  algolia.net
  algolianet.com
  googletagmanager
  hotjar
  supplyframe
  trustarc
allowed:
  arduino.cc
  ajax.googleapis.com
  cloudflare.com
  gstatic.com

Not using private browsing.

**Comment by per1234** [comment]
I can reproduce the issue.

On Win10, Chrome, Firefox, incognito/private, with two different accounts. No matter how many times I click that "Quote" button, it won't quote.

I would leave the issue open for the sake of documenting a legitimate bug (thanks @sterretjeToo!) and tracking how often it occurs. However, I have been using the quote feature every day for the last 6 years and this is the first time I've encountered this specific issue with quoting, so I don't think it needs to be considered a high priority issue.

**Comment by sterretjeToo** [comment]
I know that this is low priority so don't worry too much.

Issue is still there, checked this morning after ballscrewbob unlocked the thread.

**Comment by per1234** [comment]
I have verified that the problematic post can now be quoted with the new forum software so I'll close this as resolved. Thanks again for the report @sterretjeToo!
