### ISSUE TITLE
Sensor ventilator Help

### ISSUE THREAD

**Issue by Drsam12** [arduino/forum-issues#286]
Hi guys
It's for a ventilator (open source ) project
So I want to modify some stuff
& Kinda upgrading the app
So my probleme are in sensors ( pressure sensor , airflow sensor)
For the pressure sensor I decide to take this one:(1st picture)

The range of pressure needed(0- 5 pka) is fine (0-40 pka)

But the problem is the airflow sensor.. (0- 20/25L/MN)
I thinker about water flow sensor (0-30L/MN) {YF-S201}
That's will be work??? If no please give me some advice or , kinda of sensor that I can use for measuring the airflow
The porpus of all that it's to make an graphic , like monitoring of the ventilator(3rd picture)
Best regards
![images (25)~2](https://user-images.githubusercontent.com/68454650/89520775-493e1500-d7d6-11ea-897c-9809494b4cc1.jpeg)
![images (26)~2](https://user-images.githubusercontent.com/68454650/89520782-4a6f4200-d7d6-11ea-9c40-87714a04f25b.jpeg)
![images (44)](https://user-images.githubusercontent.com/68454650/89520786-4ba06f00-d7d6-11ea-877c-f0e4057aeb6e.jpeg)

**Comment by sterretjeToo** [comment]
This is not what github is for, so no surprise that you don't have answers.

Post your question on forum.arduino.cc (if you're using an Arduino).
