### ISSUE TITLE
Improve onboarding for new users

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#287]
One shot re-direct for noobs to a standard read-me so that most users would not need to request extra details so often.
Responders would be assured that a noob has at least been offered the chance to assess what they need to provide in terms of information.
May reduce some of the frayed tempers on occasion.
May also help reduce moderation requirements.

Situation where noob registers to use the forum.
After registration a quick re-direct to the readme before being allowed to travel to the forum.

I appreciate it will not fix everything but at least it is a start.

Having or trying some new features may also be of benefit as tests for any further forum "upgrades".
It may also breath some much needed life into the present system until such times as a new forum software comes into effect.

**Comment by leftCoast** [comment]
I really think that's the wrong approach. No one will read it. I know I never read stuff like that. Just hit spacebar a few times and get past the nonsense. Who doesn't do this?

Take the newbies to a simplified primary posting window that they can NOT mess up. Or at least its very hard to mess up.

Drop code here, enter message here, drop links here. And that;s all they can do. Then it auto formats their posts. If they want to later.. They can opt out of the auto formatter.

-jim lee

**Comment by BallscrewBob** [comment]
The amount of work involved I think would be a deciding factor.

Easiest by far would be a one shot redirect but I get where you are coming from Jim.
FORM based would also I think get some negativity and the usual round of RTM type posts.
At least with the one shot they were given info ahead of time so there are zero excuses.

I actually like Perry's post as a prime candidate for the one shot page itself as it is short and concise.
https://forum.arduino.cc/index.php?topic=703864.msg4729563#msg4729563

**Comment by leftCoast** [comment]
"Hello mpboyer3496,

Welcome to the Arduino fora. I and the other people here want to help you but to do that we need certain bits of information. Without the correct information it is difficult or impossible to give you the help and advice you need. To help us to help you please read General guidance andHow to use this forum and provide the information"

This is as far as I got. I really don't say this to be snarky, but just .. If I won't read it, who would? We need to get away from instructions and warning stickers. I'd even go for a default of having the ENTIRE post being in code tags. Let them un-code-tag it, if they can figure out how. At least that would be easy to code.

After thinking about it, I simplified my original idea to two bits,  {DRAG YOUR .INO FILE HERE} field. And an {ADD QUESTION HERE} window. Simple simple simple for mr newbie. Two sentences to read max.

-jim lee

**Comment by leftCoast** [comment]
"Hello mpboyer3496,

Welcome to the Arduino fora. I and the other people here want to help you but to do that we need certain bits of information. Without the correct information it is difficult or impossible to give you the help and advice you need. To help us to help you please read General guidance andHow to use this forum and provide the information"

This is as far as I got. I really don't say this to be snarky, but just .. If I won't read it, who would? We need to get away from instructions and warning stickers. I'd even go for a default of having the ENTIRE post being in code tags. Let them un-code-tag it, if they can figure out how. At least that would be easy to code.

After thinking about it, I simplified my original idea to two bits,  {DRAG YOUR .INO FILE HERE} field. And an {ADD QUESTION HERE} window. Simple simple simple for mr newbie. Two sentences to read max.

-jim lee

**Comment by leftCoast** [comment]
"Hello mpboyer3496,

Welcome to the Arduino fora. I and the other people here want to help you but to do that we need certain bits of information. Without the correct information it is difficult or impossible to give you the help and advice you need. To help us to help you please read General guidance andHow to use this forum and provide the information"

This is as far as I got. I really don't say this to be snarky, but just .. If I won't read it, who would? We need to get away from instructions and warning stickers. I'd even go for a default of having the ENTIRE post being in code tags. Let them un-code-tag it, if they can figure out how. At least that would be easy to code.

After thinking about it, I simplified my original idea to two bits,  {DRAG YOUR .INO FILE HERE} field. And an {ADD QUESTION HERE} window. Simple simple simple for mr newbie. Two sentences to read max.

-jim lee

**Comment by BallscrewBob** [comment]
I know that post well. However just adding a drop zone for an INO is open to all sorts of issues as a parser for the code needs to be involved which needs a custom dictionary and multiple statement checkers etc.
The add Q here box is also open to a multiple file type drop.
Where do they add pictures ?
Where do they add links ?
Where do they add PDF files ?

The list goes on.
Not every post is a code related one, so a simple two box would probably not be of much use.

**Comment by leftCoast** [comment]
You don't need a parser for the code. It just grabs the text and puts code tags around it. Regardless of what the text is.

NO pictures
NO llinks
NO PDFs

These are NEWBIES. They get a field and a comment window. PERIOD.

IF they don't like it? By their second post, they may get an option to use the standard editor.

-jim lee

**Comment by BallscrewBob** [comment]
Then we are back to the "post your pictures and links etc etc." posts so that defeats the whole idea.
Of course there will be half the posts asking how to post the rest of the post and complaining about usability and so on.
Oh and the "where is the option to turn this off" posts.

So far you have not really said anything to convince me there is any merit in the FORM type approach but quite the opposite.

**Comment by leftCoast** [comment]
Well, they said to post the comments here. So I did.

-jim lee

**Comment by BallscrewBob** [comment]
New one shot has been deployed.
