### ISSUE TITLE
Auth0 multiple browser notifications

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#290]
If a user / moderator has set the browser notifications then they may see up to 3 of the notifications in short interval succession.

Initial cause was party mitigated but also tracked to deployment time of the AUTH0.

This bug is more of a general annoyance than anything but would benefit from compete mitigation.

**Comment by per1234** [comment]
Hi . Thanks so much for reporting this bug. Since the notifications system has been completely changed by the switch to Discourse, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
