### ISSUE TITLE
Auth0 repeat emails

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#292]
Whilst similar to the browser notification this affects EMAILS.

Again it is only a recent development since AUTH0 was introduced.
In some cases it was rectified but does still happen although much less frequently.

There needs to be a complete fix for this issue which may be part of other AUTH0 issues.

An email for a reply or report may come to a users email inbox only to be shortly followed by a second or third.
Clearly unnecessary and wasteful of both system time and user time.

**Comment by jantje** [comment]
I can second that.

**Comment by per1234** [comment]
Hi @BallscrewBob. Thanks so much for reporting this bug. Since the forum email notification system has been completely changed by the switch to Discourse, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
