### ISSUE TITLE
AUTH0 (maybe) 2FA

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#293]
Although I personally dont have this issue clearly some members did / do have some issues with 2FA
https://forum.arduino.cc/index.php?topic=698486.0

**Comment by Serjlee** [comment]
The message inviting you to enable 2FA is setted up to show up once a month, is it really that annoying? 

While we could eventually tweak it, it's not really about the forum

**Comment by BallscrewBob** [comment]
For some users it clearly was annoying.
Which is why the issue was raised and placed here as requested by Allesandro.
Actually it was FORUM users that reported it so YES it is forum based even if you use it site wide.

**Comment by BallscrewBob** [comment]
Ideally it should be a single shot deal not a monthly issue. Users should be offered only once and if the decline then that is it.
They should have the ability via thier settings to enable it if they so wish in the future.
