### ISSUE TITLE
Can not zoom quick edit on Android/chrome

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/forum-issues#295]
After the forum update, I can no longer enlarge / zoom the quick edit textbox.

Android 7.0, Chrome 85.0.4183.81

**Comment by per1234** [comment]
Hi @sterretjeToo . Thanks so much for reporting this bug. Since the post composition system has been completely changed by the switch to Discourse, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
