### ISSUE TITLE
Discord "claim account bug"

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#296]
As Discord seems have been deployed as an alternate forum source it seems reasonable to use this section to report issues.

I am unable to get past a claim account or this email already exists error even if I am logged in which would suggest that it is some form of error / bug on the part of discord.

To be advised to DELETE an account and start again maybe acceptable to gamers (prime participants of discord) but would be unacceptable in a technical environment.

Continuity of a conversation is often a helping factor to engage people needing help and just coming into a conversation with a new account doe nothing to help that.
It also encourages the proliferation of sock puppets and other nefarious account along with spam.

The bug in that regard should be classed as SEVERE.

**Comment by supernova-ws** [comment]
Does not relate to forum.

**Comment by BallscrewBob** [comment]
Relates to secondary forum.

**Comment by BallscrewBob** [comment]
The FIX turns out to be quite simple but nobody on discord seemed to know what it was.

Anyway so long as you can get into any part of discord then you sim[ply LOG OUT and then LOG IN, then continue to the Arduino section.

Yes the fix that eluded the best in arduino discord is just that simple !

Closing this topic

**Comment by Edwardwsr** [comment]
Hey, you can resolve the java script error that occurred in the main process Open in Discord by reinstalling your program. To do that follow these steps one by one. just tap the Windows key or the Start button, write in the name of the program Discord and right-click on it before you choose the options Uninstall. After it has been removed, you can install the latest version from the official website. Check out more methods to fix this error by following [https://appuals.com/how-to-fix-the-a-javascript-error-occurred-in-the-main-process-error-in-discord/](https://appuals.com/how-to-fix-the-a-javascript-error-occurred-in-the-main-process-error-in-discord/) this website. In case it doesn't work then you can do it by running your program without administrative privileges. Here you need to find your program‘s executable, right-click it, press the option of Properties and then go to the Compatibility tab to uncheck the box next to Run this program as an administrator. In the end, tap OK as the issue might probably be fixed.

**Comment by ambreenmoeen** [comment]
Hey, you can resolve the java script error that occurred in the main process Open in Discord by reinstalling your program. To do that follow these steps one by one. just tap the Windows key or the Start button, write in the name of the program Discord and right-click on it before you choose the options Uninstall. After it has been removed, you can install the latest version from the official website. Check out more methods to fix this error by following https://appuals.com/how-to-fix-the-a-javascript-error-occurred-in-the-main-process-error-in-discord/ this website. In case it doesn't work then you can do it by running your program without administrative privileges. Here you need to find your program‘s executable, right-click it, press the option of Properties and then go to the Compatibility tab to uncheck the box next to Run this program as an administrator. In the end, tap OK as the issue might probably be fixed.
