### ISSUE TITLE
Discord View only

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#297]
Discord forum should be made available for non member viewing without having to sign up for discord.

The MAIN forum already has the ability to get directly there and wander around.
I presume this is just an oversight on discord that will be rectified quickly.

**Comment by supernova-ws** [comment]
Does not relate to forum.

**Comment by BallscrewBob** [comment]
Relates to the secondary forum discord.

**Comment by BallscrewBob** [comment]
Spoke to mod on discord this feature is on the roadmap.
