### ISSUE TITLE
Alerts part 2

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#299]
Currently alerts in the top toolbar works for "reported" post but fails on "quoted" posts.
The last fix may need a small tweak to account for the secondary issue which is what most regular users will see.

Part of the DECREMENT issue.

**Comment by BallscrewBob** [comment]
Seems to be AUTH0 related from the information I have.

**Comment by per1234** [comment]
Hi @BallscrewBob. Thanks so much for reporting this bug. Since the alerts system has been completely changed by the switch to Discourse, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
