### ISSUE TITLE
User disappeared?

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#30]
<a href="https://github.com/ffissore"><img src="https://avatars.githubusercontent.com/u/510465?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ffissore](https://github.com/ffissore)**
_Tuesday Oct 21, 2014 at 11:17 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/30_

----

The user that opened this thread seems disappeared:
http://forum.arduino.cc/index.php?topic=273303.0

Strange.. because an user cannot delete himself. Still, he was a new user... Were all the old users "imported" in the new forum?

**Comment by hiduino** [comment]
Thanks, but the Hawaii timezone selection in the  User profile still doesn’t work.  If you create a user and then select for Timezone [UTC-10:00] Hawaii, then the Forum web pages will be blank.  This is still not fixed.  I think this is a corrupt timezone file for Hawaii, HST.

 

hiduino

**Comment by matteosuppo** [comment]
I opened a new issue with a more meaningful name. Sorry to hear it's still not fixed :(

#184
