### ISSUE TITLE
Auto picture attach  (enhancement)

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#300]
The newly deployed austo attach pictures feature seems to have been well received.

An enhancement was requested to me to make it auto size UP to the max allowed in the forum.
many pictures get sized DOWN to actually be able to post them in the first place due to forum limitations so this minor enhancement would help and especially for those users with smaller mobile size screens or tablet devices.

**Comment by supernova-ws** [comment]
Erh... Don't think so. It will greatly increase disk usage by over-bloated images. And there is always "Zoom" option in browser (didn't saw any browser w/o it).
