### ISSUE TITLE
Read 1 time?

### ISSUE THREAD

**Issue by TLS-Rocketry** [arduino/forum-issues#303]
In some threads I come across, I see that the thread has only been read 1 time. Actually many times, cause I see 4 - 5 replies but the forum only shows 1 reply. I experienced this before the 120 day post lock.

You can see here and https://forum.arduino.cc/index.php?topic=570404.0 is just one of the threads that I saw the problem ( Please check if anyone else is facing the same ).

![Screenshot_2020-09-19 Is it possible to load webpages on a TFT display using esp8266 (1)](https://user-images.githubusercontent.com/68007313/93663853-52cec400-fa88-11ea-8671-83a3f4f3b99f.png)

**Comment by BallscrewBob** [comment]
I think it is the post time > 120 days in the case you show that has simply reset the original counter.
Don't think it is a great issue and at most may only be a minor bug.
The counts shown in the other areas are still currently correct.
![2020-09-23 at 10-00-24 correct count](https://user-images.githubusercontent.com/8212730/94023040-bc4e1b80-fd83-11ea-9c92-51316187d972.jpg)
![2020-09-23 at 10-01-01 warning count](https://user-images.githubusercontent.com/8212730/94023042-bce6b200-fd83-11ea-982d-3a6c960bb86b.jpg)

That shows the warning count as 1 yet the actual count is much higher.
I think this issue can be closed.

**Comment by TLS-Rocketry** [comment]
@BallscrewBob, I have also experienced this before the 120 day lock post deployment. It is a minor bug as you said 👍

**Comment by BallscrewBob** [comment]
Yes but the post count is as I said regardless of the new 120 day lock.
It is correct and only added when the 120 day count is passed and was the same BEFORE the auto lock.
The views as shown in the FIRST picture still reflect the ACTUAL views and NOT the 120 day counter version.

To see that open a section of the forum.
Then select the sort by views.
NOTE that the views count only really starts AFTER the sticky posts !
You can see the views column is correct.
All you are seeing is a reflection that the post has been tagged at 120> days.

**Comment by TLS-Rocketry** [comment]
Yep I tried it out....It worked! So, what you are saying is correct.

> Thinking more about it I don't even think it a bug so much as an artifact of the 120 day count.
I would agree to this now as well.
