### ISSUE TITLE
Users find it difficult to find their own posts

### ISSUE THREAD

**Issue by UKHeliBob** [arduino/forum-issues#304]
### **Problem**
There is no easy way for users to find their previous posts.  The current method requires that they open their profile, select Edit Forum settings then select Show posts.

This method is clumsy and not intuitive which leads to frustration on the part of users as well as duplicate posting when new topics are started because they can't find the old one.   If notifications are not turned on or do not work then users will sometimes think that they are being ignored

### **Solution**
Provide a link to SHOW POSTS in the same way that you can get directly to PROFILE, MESSAGES, MY PLANS and SIGN OUT by hovering the mouse pointer over your profile picture top/right of the screen

**Comment by BallscrewBob** [comment]
It is a common Q. that crops up often enough to need to be looked at for sure !
Although not official I will add it to my list.

**Comment by UKHeliBob** [comment]
Thanks for the quick implementation of a remedy to this problem
