### ISSUE TITLE
Default editor setting for forum Quick Reply

### ISSUE THREAD

**Issue by UKHeliBob** [arduino/forum-issues#305]
**Problem**
A recurring problem on the forum is code being posted without using code tags.  The most convenient way to add code tags is to use the icon in the editor toolbar but unless this option is explicitly enabled the full editor, and hence the toolbar, is not used for Quick Reply.  This makes using code tags more difficult than it needs to be.

The path to changing Quick Reply to use the full editor is convoluted ie. click on profile picture, select PROFILE, select Edit for FORUM SETTINGS,  select Settings, click Look and Layout then finally click the checkbox for "Use full editor in Quick Reply"

**Solution**
Make "Use full editor in Quick Reply" the default setting

**Comment by BallscrewBob** [comment]
I do have that on my list but AUTO, and that was rejected as being overly complex.
Also have the Editor toolbar on my list too but not quite got to that yet.

This was I think also covered in another github issue.
Could you double check that this is not a duplicate or continuation ?

**Comment by BallscrewBob** [comment]
Moved to actionable on my list and also looking as changing the text colour to red for " </> "

**Comment by UKHeliBob** [comment]
I cannot find a previous request to make the full editor the default for Quick Reply

**Comment by BallscrewBob** [comment]
It was a different request with the same outcome in that the toolbar should be displayed regardless of mode.

**Comment by BallscrewBob** [comment]
Please check to ensure this was resolved.
If it is I think you can close it.

**Comment by per1234** [comment]
Closing as obsoleted by the new forum software only having one post composition option.
