### ISSUE TITLE
New Help button obscures parts of the screen

### ISSUE THREAD

**Issue by UKHeliBob** [arduino/forum-issues#306]
The newly implemented Help button is extremely obtrusive when the forum window is used at less than full screen because it obscures part of the forum contents

I doubt that this ever tested at anything less than full screen.  If it was then whoever tested deserves a reprimand

**Comment by TLS-Rocketry** [comment]
+1 At least please make a setting where it can be disabled or best of all it's better if you remove it 👍

**Comment by JAY-M-ERICSSON** [comment]
+1 

This breaks all UI and UX rules

There are TWO (not even just one) menu bars that could host it and numerous pop down menus when it could be gently sitting ...

**Comment by BallscrewBob** [comment]
@UKHeliBob The function was removed from the forum itself.
Could you close this issue if you consider it resolved please.

**Comment by UKHeliBob** [comment]
The help button has been removed from the forum although it remains in other pages of the website but that is not a concern for me

Closing the issue

**Comment by UKHeliBob** [comment]
Issue closed
