### ISSUE TITLE
Can't change personal text in user profile

### ISSUE THREAD

**Issue by jremington** [arduino/forum-issues#307]
I am no longer able to change my Arduino forum profile "personal text" field. When I type new text into the field, then press the submit/update button, the field reverts to the original content. Other forum users report the same issue.

That is the only field I have attempted to change, so there may be other affected fields.

**Comment by TLS-Rocketry** [comment]
True. Even I faced the same problem...

**Comment by BallscrewBob** [comment]
Please see reply 297  https://forum.arduino.cc/index.php?topic=703500.285
If that fixes your issue could you close this topic please or add any extra information if it does not.

Thanks

Bob.

**Comment by jremington** [comment]
This suggestion worked, thanks!
1. Do your changes.
2. Save them
3. LOG OUT (IMPORTANT)
4. Your choice but I also close my browser and clean my cache and it may be prudent to also do it.
5. Log back in.
