### ISSUE TITLE
Email change partially reflected

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/forum-issues#308]
Good day

I've changed my email address (not sure where). It reflects on https://id.arduino.cc/?iss=https:%2F%2Flogin.arduino.cc%2F#/login but it does not reflect when I go to https://forum.arduino.cc/index.php?action=profile (still old email address).

**Comment by sterretjeToo** [comment]
Seems to be solved. Does it take time to reflect everywhere?

**Comment by BallscrewBob** [comment]
There is a time delay between changes in case a user makes a bad decision.
Used to be 7 days but I think it was reduced to 24 hrs.

**Comment by BallscrewBob** [comment]
If it is solved could you close the issue please.
