### ISSUE TITLE
expected '}' at end of input

### ISSUE THREAD

**Issue by Omerdoruk** [arduino/forum-issues#309]
ı have } in the all elses but it continues to giving me  this error i am confused: 
#include <LiquidCrystal.h>

#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C lcd(0x27,16,2);
#define irsensor 2
int sensordeger;
int durum=0;
int sayac=0;
void setup() {
  pinMode(irsensor,INPUT);
  Serial.begin(9600);
  lcd.begin(16,2);
}

void loop() {
  sensordeger=digitalRead(irsensor);

  if (sensordeger==0){

      if(durum==0){
            sayac++;
            durum=1;
            Serial.print("Sayaç: ");
            Serial.println(sayac);
            lcd.clear();
            lcd.print("Sayac: ");
            lcd.print(sayac);
            lcd.print(" Adet");
            delay(100);
      }
      delay(20);
  }
  else{
     durum=0;
  }

**Comment by BallscrewBob** [comment]
See  https://forum.arduino.cc/index.php?board=4.0
This has nothing to do with forum problems.
