### ISSUE TITLE
invalid links produced by the insert link form

### ISSUE THREAD

**Issue by ZinggJM** [arduino/forum-issues#311]
Since the new web interface got active, I can't use the "insert a link" command to produce valid links.
The links get a %22 prefix.
I am not sure if this always happens, or only if I enter a text to display.
And I don't know how I can modify a link, e.g. to change the display text.

**Comment by BallscrewBob** [comment]
This should now be rectified.
If you can still replicate please try add a link to the offending posts with a little more detail.

**Comment by ZinggJM** [comment]
Yes, it works now, thank you.
I keep the issue open, because of a remaining issue: the link is still wrong in the preview window. Can lead to confusion of the poster.
Related forum post: https://forum.arduino.cc/index.php?topic=712157.msg4784666#msg4784666

**Comment by per1234** [comment]
Hi @ZinggJM.

> the link is still wrong in the preview window

Is this bug still occuring? If so, would you mind providing a more detailed description of the problem, with a specific set of steps I can use to reproduce it? I did read that forum post, but I still didn't understand what the problem is.

**Comment by ZinggJM** [comment]
I think I did encounter this issue recently with preview window still.
**But with the new forum version it is fixed. Thank you.**
