### ISSUE TITLE
incorrect links in search results (wrong page)

### ISSUE THREAD

**Issue by ZinggJM** [arduino/forum-issues#312]
The links from search results don't work. The effect is that the first post is shown instead of the post found.
Example: I searched for "e-paper shield".
One of the results is: 
https://forum.arduino.cc/?topic=487007#msg4203283
the correct page result would be:
https://forum.arduino.cc/?topic=487007.msg4203283
the correct result would be: (copy link from post)
https://forum.arduino.cc/index.php?topic=487007.msg4203283#msg4203283

**Comment by BallscrewBob** [comment]
Cannot replicate here and all the links you provided appear to be valid and to the same post.
In addition if I use "e-paper shield" as the search term (no quotes) you are top of the pile without even sorting.

https://www.arduino.cc/search?tab=forum&q=e-paper+shield

**Comment by ZinggJM** [comment]
Yes, the links are valid (sorry for the wrong title), but the first two are not correct.
The first link brings up page 1 of the topic.
The second link brings up top of page 90.
The third link brings up page 90 positioned to the correct post.
Tested on actual Windows 10 Edge browser using "open link in new tab".

**Comment by per1234** [comment]
Hi @ZinggJM. Thanks so much for reporting this bug! I just gave it a try and it looks like the URLs now have the correct form to take you to the topic and also the specific post number in that topic where the search result match was found.

So I'm going to close this as fixed. If you find the bug with the forum search is still there, please feel free to comment here and I'll reopen this issue.

**Comment by ZinggJM** [comment]
Thank you, the links found work with the new forum version.
