### ISSUE TITLE
stray '\342' in program error

### ISSUE THREAD

**Issue by Omerdoruk** [arduino/forum-issues#315]
Arduino:1.8.13 (Windows 10), Kart:"Arduino Uno"

sketch_nov09a:13:11: error: stray '\342' in program

sketch_nov09a:13:12: error: stray '\200' in program

sketch_nov09a:13:13: error: stray '\234' in program

sketch_nov09a:13:29: error: stray '\342' in program

sketch_nov09a:13:30: error: stray '\200' in program

sketch_nov09a:13:31: error: stray '\235' in program

sketch_nov09a:20:6: error: stray '\342' in program

sketch_nov09a:20:7: error: stray '\200' in program

sketch_nov09a:20:8: error: stray '\223' in program

sketch_nov09a:22:11: error: stray '\342' in program

sketch_nov09a:22:12: error: stray '\200' in program

sketch_nov09a:22:13: error: stray '\234' in program

sketch_nov09a:22:29: error: stray '\342' in program

sketch_nov09a:22:30: error: stray '\200' in program

sketch_nov09a:22:31: error: stray '\235' in program

sketch_nov09a:30:11: error: stray '\342' in program

sketch_nov09a:30:12: error: stray '\200' in program

sketch_nov09a:30:13: error: stray '\234' in program

sketch_nov09a:30:29: error: stray '\342' in program

sketch_nov09a:30:30: error: stray '\200' in program

sketch_nov09a:30:31: error: stray '\235' in program

sketch_nov09a:36:11: error: stray '\342' in program

sketch_nov09a:36:12: error: stray '\200' in program

sketch_nov09a:36:13: error: stray '\234' in program

sketch_nov09a:36:29: error: stray '\342' in program

sketch_nov09a:36:30: error: stray '\200' in program

sketch_nov09a:36:31: error: stray '\235' in program

sketch_nov09a:51:11: error: stray '\342' in program

sketch_nov09a:51:12: error: stray '\200' in program

sketch_nov09a:51:13: error: stray '\234' in program

sketch_nov09a:51:28: error: stray '\342' in program

sketch_nov09a:51:29: error: stray '\200' in program

sketch_nov09a:51:30: error: stray '\235' in program

sketch_nov09a:53:11: error: stray '\342' in program

sketch_nov09a:53:12: error: stray '\200' in program

sketch_nov09a:53:13: error: stray '\234' in program

sketch_nov09a:53:26: error: stray '\342' in program

sketch_nov09a:53:27: error: stray '\200' in program

sketch_nov09a:53:28: error: stray '\235' in program

sketch_nov09a:5:1: error: 'define' does not name a type; did you mean 'rewind'?

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino: In function 'void IN()':

sketch_nov09a:11:1: error: 'count' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:11:1: note: suggested alternative: 'round'

sketch_nov09a:13:14: error: 'Person' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:13:14: note: suggested alternative: 'perror'

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino: In function 'void OUT()':

sketch_nov09a:20:1: error: 'count' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:20:1: note: suggested alternative: 'round'

sketch_nov09a:22:14: error: 'Person' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:22:14: note: suggested alternative: 'perror'

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino: In function 'void setup()':

sketch_nov09a:30:14: error: 'Visitor' was not declared in this scope

sketch_nov09a:32:9: error: 'in' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:32:9: note: suggested alternative: 'sin'

sketch_nov09a:33:9: error: 'out' was not declared in this scope

sketch_nov09a:34:9: error: 'relay' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:34:9: note: suggested alternative: 'delay'

sketch_nov09a:36:14: error: 'Person' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:36:14: note: suggested alternative: 'perror'

sketch_nov09a:38:11: error: 'count' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:38:11: note: suggested alternative: 'round'

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino: In function 'void loop()':

sketch_nov09a:42:16: error: 'in' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:42:16: note: suggested alternative: 'sin'

sketch_nov09a:44:16: error: 'out' was not declared in this scope

sketch_nov09a:46:4: error: 'count' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:46:4: note: suggested alternative: 'round'

sketch_nov09a:49:14: error: 'relay' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:49:14: note: suggested alternative: 'delay'

sketch_nov09a:51:14: error: 'Nobody' was not declared in this scope

sketch_nov09a:53:14: error: 'Light' was not declared in this scope

sketch_nov09a:57:14: error: 'relay' was not declared in this scope

C:\Users\ŞERAFETTİN\Desktop\sketch_nov09a\sketch_nov09a.ino:57:14: note: suggested alternative: 'delay'

exit status 1

stray '\342' in program

C:\Program Files (x86)\Arduino\libraries\LiquidCrystal-1.0.6 içerisinde geçersiz kütüphane bulundu: no headers files (.h) found in C:\Program Files (x86)\Arduino\libraries\LiquidCrystal-1.0.6

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by TLS-Rocketry** [comment]
Not forum related...

**Comment by BallscrewBob** [comment]
See the link below for your problem 

https://forum.arduino.cc/
