### ISSUE TITLE
@username functionality not working

### ISSUE THREAD

**Issue by UKHeliBob** [arduino/forum-issues#317]
The functionality whereby an alert would be raised for "username" when @username forms part of a post was recently reinstated.  However, it now appears not to be working

Has it been deliberately removed ?

**Comment by per1234** [comment]
According to this forum post, yes:
https://forum.arduino.cc/index.php?topic=716436

**Comment by BallscrewBob** [comment]
Three users complained of excessive alerts.
Since been reasoned that they are not all linked to the @username feature and that one user may be misunderstanding the usage.

Hope to re-enable quite soon maybe as early as next week.

**Comment by UKHeliBob** [comment]
When is it anticipated that this functionality will be reinstated ?

**Comment by jantje** [comment]
The spurious alerts that started with activating this feature are still there. So there is no reason not to reactivate for me :-s

**Comment by BallscrewBob** [comment]
Have asked for @username to be re-enstated.

**Comment by UKHeliBob** [comment]
Is there any news on the fix being implemented ?

**Comment by BallscrewBob** [comment]
I have not heard or seen anything.

**Comment by BallscrewBob** [comment]
BUMP

**Comment by UKHeliBob** [comment]
Bump from me too

If this is not going to be fixed because of the planned move to Discourse then please say so

**Comment by BallscrewBob** [comment]
@UKHeliBob It's simply a toggle to turn this back on.
Not particularly hard but its a level above our pay grade.

![image](https://user-images.githubusercontent.com/8212730/112150087-148c9b80-8bb6-11eb-8782-551403677906.png)

**Comment by per1234** [comment]
Thanks so much for taking the time to submit this issue @UKHeliBob. "@" mentions on the Arduino forum are now back for good with the switch to the Discourse forum software so I'll close this as resolved.
