### ISSUE TITLE
Auth0 change font react

### ISSUE THREAD

**Issue by juliettemahieu** [arduino/forum-issues#322]
Hello everyone,

I made a lot of research on how to change the some options of auth0 and I'm really stuck. I understand for example that I need to use 

  var options = {
    languageDictionary: {
      title: "title"
    },
  };

to change the title but where do I use the options variable. I've seen it use in index.js like 

  ReactDOM.render(
    <Auth0Provider
    domain="my_domain.auth0.com"
    clientId="my_password"
    options={options}
    redirectUri={window.location.origin}
    >
      <App />
    </Auth0Provider>,
    document.getElementById("root")
  );

But it doesn't work. Does anyone know how to modify the front of auth0 ? 
Thank you in advance

**Comment by per1234** [comment]
Hi @juliettemahieu. Thanks for your interest in the Arduino project.

Your question doesn't appear to be related to a defect or enhancement in the Arduino Forum software, so close this as off topic.

If I have incorrectly interpreted the subject matter, please comment here with more information and I'll evaluate whether it should be re-opened.
