### ISSUE TITLE
forum.arduino.cc still seems to be down

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/forum-issues#324]
Using different devices and browsers and they all exhibit the same behaviour (currently 502 errors)

Windows 10 plus firefox/chrome/edge.
1) I normally don't use Edge and I never visited forum.arduino.cc with it so it's not a matter of cache / cookies etc.
2) Cleared the cache in Firefox, issue still persists,

Android plus chrome

Please advise if
the issue was resolved at your side and I have to take it further at my side
or
that it's still going on at your side.

Thanks in advance.

**Comment by sterretjeToo** [comment]
From an end-user perspective, it seems to be solved. However, as it is labeled as "bug", I will not close it.

**Comment by BallscrewBob** [comment]
There are a few suggestions within this thread for additional actions https://forum.arduino.cc/t/forum-in-updateprogress/1086337/48
