### ISSUE TITLE
504 gateway timeout, 502 bad gateway

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/forum-issues#326]
Firefox and Chrome on Windows 10; cleared cookies and cache
Chrome on Android

Two different ISPs

I picked it up at around 9:50 SAST with a 504

Anybody else?

**Comment by per1234** [comment]
Thanks for the report @sterretjeToo. I have also been experiencing this outage/service degradation.

**Comment by sterretjeToo** [comment]
Out of curiosity, is the root cause of the issue known?

Below might help in solving

I could get in using Chrome on Windows 10. tried to post a topic there and was prompted that the message was edited in another window; I did not reload.
Next tried to post the topic but got a 503 popup (discourse style as far as I could see).

**Comment by sterretjeToo** [comment]
Retried to post on the forum after posting above message and it 'worked'.

**Comment by sterretjeToo** [comment]
Issue no longer shows its face. Holding thumbs ;)

**Comment by per1234** [comment]
I also haven't experienced the problem any more after service was restored shortly after the time of the report. So I'll close this as resolved. Thanks for the report @sterretjeToo!
