### ISSUE TITLE
 Value is not passed between base and derived class?

### ISSUE THREAD

**Issue by GitHubedklam** [arduino/forum-issues#327]
Derived Class cannot update Base class variable value?  Value is not passed between base and derived class? Static cannot be use in declaration ?
//==================================================
#include <Arduino.h>
/ /base class
class Parent {

  // protected data members
protected:
  int id_protected;

public:
  int finalID;  // cannot use static ??

public:
  void printParent() {
    Serial.println("id_protected in Parent is:");
    Serial.println(id_protected);
    Serial.println("id_protected in Parent via finalID is:");
    Serial.println(finalID);
  }
};

// sub class or derived class from public base class
class Child : Parent {

protected:

  String ChildName;  // protected

public:

  int setId(int id) {

    // Child class is able to access the inherited
    // protected data members of base class

    id_protected = id;

    finalID = id_protected;  // ***compile erroe if static was declared earlier ???

    return id_protected;
  }

  void displayId() {
    Serial.println("id_protected is:");
    Serial.println(id_protected);
  }
};

class Child2 : Parent {
public:
  int newID(int multiply) {

    Serial.println("id_protected from Child2 A is:");
    Serial.println(id_protected);
    id_protected = id_protected * multiply;  // sub class accessable to protected parant member but value wrong ????
    Serial.println("id_protected from Child2  B is:");
    Serial.println(id_protected);
    return id_protected;
  }
};

// main function
void setup() {

  Serial.begin(9600);

  Parent myParent;

  Child obj1;

  // member function of the derived class can
  // access the protected data members of the base class
  myParent.printParent();  //  somehow the value id_protected set earlier is not passed from child to parent ?

  obj1.setId(81);
  myParent.printParent();
  obj1.displayId();

  Child2 newObj;
  newObj.newID(2);

  myParent.printParent();

  // Serial.println(myParent.finalID);

}

void loop() {}

//=============================================

the results output :

id_protected in Parent is:
-14590
id_protected in Parent via finalID is:
-14846
id_protected in Parent is:
-14590
id_protected in Parent via finalID is:
-14846
id_protected is:
81
id_protected from Child2 A is:
0
id_protected from Child2  B is:
0
id_protected in Parent is:
-14590
id_protected in Parent via finalID is:
-14846

**Comment by per1234** [comment]
Hi @GitHubedklam. Thanks for your interest in the open source Arduino project. This issue tracker is only to be used to report bugs or feature requests specific to the Arduino Forum software. This topic is more appropriate for discussion on the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
