### ISSUE TITLE
Fixed width for code in messages, add scrollbar

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#44]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Tuesday Oct 21, 2014 at 15:54 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/44_

---

https://basecamp.com/2546761/projects/6328288

**Comment by per1234** [comment]
Closing as obsolete.
