### ISSUE TITLE
Custom code formatted

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#51]
<a href="https://github.com/ffissore"><img src="https://avatars.githubusercontent.com/u/510465?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ffissore](https://github.com/ffissore)**
_Wednesday Oct 22, 2014 at 10:09 GMT_
_Originally opened as https://github.com/arduino/forum2/pull/51_

---

This PR makes it easier to compare files from theme "Arduino2x-Theme" with files from theme "default"
It also add `.editorconfig` file in repo's root

---

_**[ffissore](https://github.com/ffissore)** included the following code: https://github.com/arduino/forum2/pull/51/commits_

**Comment by per1234** [comment]
I'm sure it was a wonderful PR, but this is an issue tracker so it is irrelevant here.
