### ISSUE TITLE
Forcing User Preferences

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#60]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Wednesday Oct 22, 2014 at 13:06 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/60_

---

You can change this in your settings ("Show most recent posts at the top in topic view."), looks like this option reverted to bottom up after the upgrade.

You may also need to change "Return to topics after posting by default." as that was reset as well and causes you to return to the forum not the thread you just posted to.

![21-10-2014 9-40-31 am](https://cloud.githubusercontent.com/assets/6151328/4736404/2f77774c-59ec-11e4-8cf0-f9268ca1e028.jpg)

**Comment by per1234** [comment]
Default settings of the forum now provide the desired recent on top and stay in thread after posting behavior.
