### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#66]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Wednesday Oct 22, 2014 at 16:22 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/66_

---

sent items

![screenshot 2014-10-22 18 21 33](https://cloud.githubusercontent.com/assets/6151328/4739820/90caca60-5a07-11e4-82f0-f8ff28a962f4.png)

**Comment by per1234** [comment]
Closing as obsoleted by the switch to a Discourse based forum this week.
