### ISSUE TITLE
Add New Message/Show draft button to Messages dropdown

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#73]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Thursday Oct 23, 2014 at 11:28 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/73_

---

Currently not showing up for Newbies and Moderators alike

**Comment by matteosuppo** [comment]
Hello, can you please tell me what do you mean?

**Comment by per1234** [comment]
Closing due to lack of feedback.
