### ISSUE TITLE
All Main Nav dropdown not working on iOS7

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#74]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Thursday Oct 23, 2014 at 13:02 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/74_

----

This is really critical, users cannot navigate the website, get to their profile/messages or sign out

cc @mastrolinux @madbob @danielebarbaro

**Comment by mastrolinux** [comment]
Works now, @matteosuppo can we close this one?
