### ISSUE TITLE
Change Title style

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#77]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Thursday Oct 23, 2014 at 15:39 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/77_

---

Change Board titles stye from this:
![screenshot 2014-10-23 17 13 15](https://cloud.githubusercontent.com/assets/6151328/4756056/98dbea4a-5aca-11e4-8054-083ac2acc5a2.png)

To the same as Topic titles style:
![screenshot 2014-10-23 17 42 10](https://cloud.githubusercontent.com/assets/6151328/4756144/2b1edcfa-5acb-11e4-926e-69d83fdb0444.png)

**Comment by per1234** [comment]
Since the forum layout has been completely changed by the switch to Discourse, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
