### ISSUE TITLE
Cannot merge threads

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#82]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Friday Oct 24, 2014 at 08:26 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/82_

---

https://basecamp.com/2546761/projects/6328288/todos/133503294#comment_211946270

**Comment by nickgammon** [comment]
Still can't merge threads across different parts of the forum. Anyone going to work on this?

**Comment by nickgammon** [comment]
Higher priority on this please.

**Comment by per1234** [comment]
I have not encountered anything similar to this annoying bug since the switch to the Discourse-based forum this week.

If anyone encounters bugs when merging threads, please open a new issue.
