### ISSUE TITLE
Notifications not being received

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#83]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Friday Oct 24, 2014 at 08:29 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/83_

----

It seems like there is an issue in saving the Preferences.

https://basecamp.com/2546761/projects/6328288/todos/133503882#comment_211947247

**Comment by nickgammon** [comment]
Can we re-open this? I haven't received any notifications for months. Refer to https://github.com/arduino/forum-issues/issues/158 which discusses a similar issue and is open.

**Comment by nickgammon** [comment]
Example thread: http://forum.arduino.cc/index.php?topic=172578.msg1976346#new

![screenshot from 2015-01-10 06 14 31](https://cloud.githubusercontent.com/assets/185088/5685623/0c212058-9890-11e4-8ed9-13ffb82a3d8e.png)

Notice I am following it (the little spectacles) and there is a "new" tag.

---

My notification preferences:

![screenshot from 2015-01-10 06 16 54](https://cloud.githubusercontent.com/assets/185088/5685641/4f11c2aa-9890-11e4-83aa-e998a0e86871.png)

You can see that I want notifications "straight away" and by email, if a topic I follow gets a reply.

---

Below is my email program (the part that has the Arduino messages):

![screenshot from 2015-01-10 06 19 03](https://cloud.githubusercontent.com/assets/185088/5685673/aac07704-9890-11e4-874f-a478f37ee82c.png)

You can see that I am getting notifications of personal messages (hence my email address is correct) however not a single notification of any threads in the entire year of 2015.

---

Below are my "watched threads":

![screenshot from 2015-01-10 06 21 16](https://cloud.githubusercontent.com/assets/185088/5685699/f5b11d36-9890-11e4-88e1-c1faa7f0a66b.png)

There are hundreds of threads I should be getting notifications for, and you can see that the preferences is to "receive emails and alerts". Well, I'm just not getting them.

---

Check out this thread on the forum: http://forum.arduino.cc/index.php?topic=279661.msg2011196#msg2011196

That post, for example:

> Thanks Graham, no notification though even with the extra two posts. The system is still broken AFAICT and yet the bug has been closed...go figure.
> Maybe I'll drop in next year and see how it's going :)

It's not just me.

**Comment by mastrolinux** [comment]
It can be related to old posts. I noticed new posts work correctly while
old ones do not.
Il 09/gen/2015 20:27 "Nick Gammon" <notifications@github.com> ha scritto:

**Comment by nickgammon** [comment]
I have not got any notifications for months. I make posts every day. There is more to it than that. Usually my posts get replied to.

Besides, if the database shows a whole heap of posts that I should get a notification for, it should be simple enough to reply to one of them, and then put debugging into the forum to see if the notification got sent.

**Comment by nickgammon** [comment]
Is this relevant?

https://github.com/SimpleMachines/SMF2.1/issues/2561

Why are we using a Beta version of the forum?

From http://www.simplemachines.org/community/index.php?topic=530233.0 :+1: 

> Warning! This is just the first beta! There ARE bugs and incomplete features; it is not recommended that you run this release on a live/production site.

This is a major production site here, and we are running a version not recommended for production. Surely this in itself is the first error?

**Comment by nickgammon** [comment]
I tested with an alt (Miran Ligowyr) who is subscribed to http://forum.arduino.cc/index.php?topic=279661.

No notifications or emails are being received.

I challenge you guys to make a new forum member, subscribe to a topic, make a post to that topic on your main account, and see if you get a notification.

**Comment by nickgammon** [comment]
Is SMF writing an error log? Does this show anything useful?

**Comment by mastrolinux** [comment]
We found a bug in the settings profile that affects the notification system. We have a pullvrequest already thet will be released on Monday morning.

**Comment by nickgammon** [comment]
Which Monday did you have in mind? I make it 6:58 AM on **Tuesday** in Italy, and I am not getting notifications still.

**Comment by nickgammon** [comment]
I am getting notifications now, thank you. Now please fix up things like this:

![screenshot from 2015-01-14 08 10 53](https://cloud.githubusercontent.com/assets/185088/5729234/012d4a90-9bc5-11e4-8845-629b5fa38cba.png)

I don't want all the \&nbsp; and \<br\> stuff. That makes it unreadable. The notification should be of the post before converting into HTML.

The post actually looks like this:

![screenshot from 2015-01-14 08 13 56](https://cloud.githubusercontent.com/assets/185088/5729268/551448ca-9bc5-11e4-80ff-372d58f12480.png)

**Comment by nickgammon** [comment]
Some notifications are still (apparently) not being received. For example I subscribe to this thread in Bar Sport:

![screenshot from 2015-01-14 15 54 39](https://cloud.githubusercontent.com/assets/185088/5734303/bbe5ecfc-9c06-11e4-93af-411e2ad56728.png)

As you can see, a post was made at 2:45 pm and I am subscribed to it. However I have not received an email about that 17 minutes later. (Actually it is 4:02 PM here but that is because the forum time is out by an hour - see https://github.com/arduino/forum-issues/issues/164 ).

I don't necessarily expect mail one minute later, but I think 15 minutes is reasonable for the forum to be sending notifications. After all, it there is a big queue, waiting 15 minutes will only allow the queue to get longer.

**Comment by nickgammon** [comment]
A post was made to a thread here: http://forum.arduino.cc/index.php?topic=291098.msg2042977#msg2042977

I got no notification about that response, hours later. It seems that notification are at best, only partly working.

If the developer working on this (and I see that "no one" is assigned to this bug) would like to subscribe to (say) 100 threads, and then check that they get a notification **to each one** as they are made, that would help. You can always make an alt account and post responses yourself.

**Comment by Elijahg** [comment]
As Nick Gammon says, why is such a large site using a beta version of SMF? That's ridiculous, especially since the devs at SMF strongly recommend that you do not use this version on a production site. 

What happens if the database gets wrecked? You just revert back a few weeks losing heaps of posts? What if there's a critical security bug and everyone's details get leaked? Come on people, this is unprofessional at best, we had no problems with the last version!

...And while we're at it, what happened to the real search?

**Comment by nickgammon** [comment]
Can we do something about my comment above about the HTML in emails? It is distracting. Plus I **don't have that option set** anyway.

![screenshot from 2015-01-19 07 42 48](https://cloud.githubusercontent.com/assets/185088/5793999/106d56ec-9faf-11e4-915d-28e9ebeba457.png)

A wall of HTML is annoying, and with the option unchecked I should not be receiving it. So that's two bugs.

**Comment by mastrolinux** [comment]
@nickgammon do you still encounter the problem with html tags?

**Comment by nickgammon** [comment]
Yes, this is a notification I got today:

```

View the reply at: http://forum.arduino.cc/index.php?topic=318385.new#new

Unsubscribe to this topic by using this link: http://forum.arduino.cc/index.php?action=notifyboard;board=4.0

The text of the reply is shown below:
sli() was a typo.  It's actually sei().<br><br>Here's the code.<br><br>[code]// Pin mapping<br>const byte GSCLK = 3;<br>const byte VPRG = 4;<br>const byte XLAT = 9;<br>const byte BLANK = 10;<br>const byte SIN = 11;<br>const byte SCLK = 13;<br><br>// The order of the tricolour legs (L2R) to ensure the right colour comes on! <br>const byte RED_L = 2;<br>const byte GREEN_L = 1;<br>const byte BLUE_L = 0;<br><br>// Controls the current through the LEDs 
```

I truncated it, but basically the "text of the reply" is a single long line, with newlines turned into \<br\> inside it.  It's like the mailer is sending the HTML version, not the text version.

It seems to be a multi-part message if I look at the email source. First part:

```
Content-Type: multipart/alternative; boundary="SMF-ed37fffaca0ba4e83f1b66d1567805d7"
Content-Transfer-Encoding: 7bit
```

Second part:

```
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit
```

Both parts have the \<br\> in them. This particular message doesn't seem to have \&nbsp; in it, however that is quite common.

First part of header, to help you find the script in question:

```
Subject: Topic reply: Re: Timer1 Frequency will not change!
X-PHP-Originating-Script: 1000:ScheduledTasks.php
From: Arduino Forum <webmaster@arduino.cc>
Date: Sat, 25 Apr 2015 09:29:38 +0000
Message-ID: <0000014cefe92dd7-4c857ec7-ec3b-41e3-8bc1-76a9499f311a-000000@email.amazonses.com>
X-Mailer: SMF
```

**Comment by nickgammon** [comment]
I'm wondering when this will be fixed? As usual, I got today a notification like this:

```
The text of the reply is shown below:
Thanks for all this knowledge.<br><br>I really need to digest it while at the same time I build my library.<br><br>The __builtin_avr_delay_cycles() will come in handy, even though I do want to become<br>comfortable in writting short ASM segments for AVR (and later ARM I suppose). That'll handle<br>all AVRs chips 4MHz to up to the 60+MHz out there I think.<br><br>I know the timings of the WS2812B and understand them pretty well. I'm quite seasoned<br>in CS skills and grok how chips are designed, assemblers do their work and what code does.<br><br>I'm just very new to AVR and Arduino, and bare bones ASM (I usually at most use C built ins<br>for the few special atomic instructions). I picked it up on a whim (a friend gave me an uno<br>and it opened the floodgates) and now I wanna contribute and build a few cool things for<br>*hum* the next burning man :P.<br><br>Question is there room for yet another WS2812 library out there? XD
```

All those "br" tags make it pretty unreadable. Surely this is a simple fix? The raw post doesn't have them, so send the raw post in the email, don't do the nl2br() function call.

I reported this in January this year. It is now June, marked "bug" and "critical". Also "no one assigned". (sigh)

**Comment by mastrolinux** [comment]
Hi @nickgammon,

This was fixed by SMF base code. We are trying to merge the stable version of SMF 2 in our codebase but takes a while. I will now ask one developer to stop doing that for a while and fix this issue.

**Comment by mastrolinux** [comment]
Hello @nickgammon notification only and email only should be now active, can you please test it? We are working on removing html tags in emails as well.

Thank you

**Comment by nickgammon** [comment]
I still have notifications turned off (as in the screenshot above) and got a notification about 3 hours ago (amongst others). Still with the HTML in it as well.

**Comment by ffissore** [comment]
I have notification turned ON and I don't receive them

**Comment by 00alis** [comment]
As well I am not receiving Notifications from the Arduino Create Betatesting board, it works just the very same day I press the RECEIVE EMAILS button and then it stops.

**Comment by mastrolinux** [comment]
This is because settings are reverted, Matteo is working on this.

**Comment by mastrolinux** [comment]
now in production.
