### ISSUE TITLE
[code] is not colored. time for [arduino]

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#90]
<a href="https://github.com/ffissore"><img src="https://avatars.githubusercontent.com/u/510465?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ffissore](https://github.com/ffissore)**
_Friday Oct 24, 2014 at 16:04 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/90_

---

As shown by this user http://forum.arduino.cc/index.php?topic=274486.msg1933839#msg1933839 a nice syntax colouring is already achievable. It may be easy to introduce the [arduino] tag. 

```
[arduino]
void setup() {
}

void loop() {
}
[/arduino]
```

**Comment by nickgammon** [comment]
See: http://forum.arduino.cc/index.php?topic=330499.msg2280952#msg2280952

The forum colours PHP code inside code tags (which is not relevant here), but not C++ code, which is. How about supporting C++ code tags? (Either by self-detection, or making it the default).

**Comment by per1234** [comment]
Syntax highlighting is now available after the switch to using the Discourse forum software this week.
