### ISSUE TITLE
Remove a redirect link

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#96]
<a href="https://github.com/00alis"><img src="https://avatars.githubusercontent.com/u/6151328?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [00alis](https://github.com/00alis)**
_Monday Oct 27, 2014 at 09:02 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/96_

----

https://basecamp.com/2546761/projects/6328288/todos/133531590

**Comment by matteosuppo** [comment]
There's no way to remove a single redirect, but you can use this (admin-only) way:

http://forum.arduino.cc/index.php?action=admin;area=maintain;sa=topics;

It can remove all posts which are moved topic notices in all boards or certain boards
