### ISSUE TITLE
Cannot use URL in signature

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#98]
<a href="https://github.com/nickgammon"><img src="https://avatars.githubusercontent.com/u/185088?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nickgammon](https://github.com/nickgammon)**
_Tuesday Oct 28, 2014 at 23:04 GMT_
_Originally opened as https://github.com/arduino/forum2/issues/98_

----

I tried to change my forum signature to this:

```
[color=darkslateblue]Please post technical questions on the forum, not by personal message. Thanks![/color]
[url=http://www.gammon.com.au/electronics]http://www.gammon.com.au/electronics[/url]
```
I got an error message:

> The following errors occurred when trying to save your profile:
>
>    The following BBC is not allowed within your signature: abbr, acronym, anchor, bdo, black, blue, br, center, code, email, flash, font, ftp, glow, green, html, hr, i, img, left, li, list, ltr, me, member, move, nobbc, php, pre, quote, red, right, rtl, s, shadow, size, sub, sup, table, td, time, tr, tt, u, white

However the two codes I used (color and url) are not on the disallowed list!

I removed the "url" one and it was accepted. However a lot of people put urls in their signatures (or we used to be able to) as a reference to our own web sites.

**Comment by ElectricRCAircraftGuy** [comment]
I am having the exact same issue. I get the same error as Nick Gammon, as shown at the top of his screenshots. Also, like Nick, this is when I am using the "url" tag, which, like Nick pointed out, is not in the list.
